### PR TITLE
Developer Enhancement: add local docs build/run container tooling

### PR DESCRIPTION
**Pull request by usrbinkat**
### Summary
This PR adds container build & run tooling for developing docs against a local container which meets all deps.

### Reason
[JIRA DEVREL-334](https://konghq.atlassian.net/browse/DEVREL-334?atlOrigin=eyJpIjoiOWQ1ZTk1MzE3MWQwNGRhZmFlMDI1YjU3YWRkNzQ0OWUiLCJwIjoiaiJ9) Authored due to general concern with environment delta & drift when developing against un-like environments.

### Testing
```sh
git clone --branch feature-devel-container https://github.com/usrbinkat/docs.konghq.com ~/docs-feature-devel-container
cd ~/docs-feature-devel-container
./hack/build-container.sh
./hack/run-container.sh
make install && make run
```

### CODE REVIEW

**Comment by mheap** [comment]
We used to have a Docker setup but it didn't really work, and was _very_ slow when performing disk I/O on MacOS. If we want to support Docker as an official contribution method, should we make this a `docker-compose` setup so it's as simple as `docker-compose up`?

**Comment by Guaris** [comment]
This hangs for me while trying to start Jekyll. 
How long did it take you to run `build-container.sh`? It took me 75 minutes. I feel like that might not be ideal.

**Comment by usrbinkat** [comment]
> This hangs for me while trying to start Jekyll. How long did it take you to run `build-container.sh`? It took me 75 minutes. I feel like that might not be ideal.

On my intel mac, it never came up, it spins up pretty quickly on linux.

**Comment by usrbinkat** [comment]
> What's the plan to move forward here? Fix on MacOS, add docker-compose or close the PR?

there is no fix on mac, i can add integrate with the existing docker-compose.

**Comment by mheap** [comment]
Feel free to rewrite the existing docker-compose, it's not used anywhere

> there is no fix on mac

If this is the case, we can't publish this in the repo. We need to work on at least macos + Linux

**Comment by mheap** [comment]
Closing this out until we can time to dedicate to building a cross-platform environment

**Pull request closed without merging**
