### PR TITLE
Docs/mesh helm install improvement

### PR DESCRIPTION
**Pull request by andrewgkew**
### Review

@reviewer

### Summary

This change is updating the docs for installing mesh using helm. By default the license config is commented out and so is not applied to mesh on install, this needs to be overwritten for it to work, so added docs on how to do that.

### Reason

Reason I am making this change is because there are no docs about how to apply the license for mesh and by default it does not apply the license even though the docs say create a secret with the license in. The config needs to be adjusted in order for this to work.

### Testing

Testing the change is very easy, install mesh without the switch and then with the switch and you will see it not apply and then apply.

Not apply license:

helm upgrade -i -n kong-mesh-system kong-mesh kong-mesh/kong-mesh

Apply license:

helm upgrade -i -n kong-mesh-system kong-mesh kong-mesh/kong-mesh \
        --set kuma.controlPlane.secrets[0].Env="KMESH_LICENSE_INLINE" \
        --set kuma.controlPlane.secrets[0].Secret="kong-mesh-license" \
        --set kuma.controlPlane.secrets[0].Key="license.json"

### CODE REVIEW

**Comment by lahabana** [comment]
Thanks @andrewgkew going to look at this later this week.

**Comment by andrewgkew** [comment]
Thanks for the suggestion @lahabana 

I do agree that does seem a lot more to the point, and just creating the part of values you want to override I guess makes sense.

Why dont we simply it even more and just use the --set parameters to configure the fields on install rather than doing an upgrade after? And have that as the third set, the second creating the secret?

```
helm repo add kong-mesh https://kong.github.io/kong-mesh-charts && helm repo update
```

```
kubectl create secret generic kong-mesh-license -n kong-mesh-system --from-file=/path/to/license.json
```

```
helm install --create-namespace --namespace kong-mesh-system kong-mesh kong-mesh/kong-mesh
--set kuma.controlPlane.secrets[0].Env="KMESH_LICENSE_INLINE"
--set kuma.controlPlane.secrets[0].Secret="kong-mesh-license"
--set kuma.controlPlane.secrets[0].Key="license.json"
```

Then there is 1 less step? Or do you think the overriding in the helm command is more complex than using a values file?

**Comment by andrewgkew** [comment]
@lahabana - I have pushed a change based on our convo today let me know what you think

**Review by lahabana — APPROVED** [review]

**Comment by lahabana** [comment]
Thanks!

**Comment by andrewgkew** [comment]
@Bradamant3 Out of interest whats the release cycle on getting this merged?

**Comment by lena-larionova** [comment]
@andrewgkew apologies, there was a bit of a miscommunication in our team on who needs to merge this and when. The reminder is much appreciated!

**Comment by andrewgkew** [comment]
@lena-larionova - thanks for the merge :) when does this get pushed into the actual documentation? Is it an overnight process?

**Comment by lena-larionova** [comment]
> @lena-larionova - thanks for the merge :) when does this get pushed into the actual documentation? Is it an overnight process?

Thanks for following up. Generally, once a PR is merged into main, the changes will be live in 15-20 minutes, which yours are: https://docs.konghq.com/mesh/1.3.x/installation/helm/.
Except they're not in the latest version, since Mesh 1.4 was released between the time this PR was created and then merged, and we missed that. Opened https://github.com/Kong/docs.konghq.com/pull/3173 to handle that.

**Pull request merged**
