### PR TITLE
remove redundant ui elements

### LINKED ISSUE #962: Refactor docs page titles and header for clarity
screenshot_10_19_18__10_59_am

### PR DESCRIPTION
**Pull request by tingaloo**
**NOTE**: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md

### Summary

Remove redundant ui elements as per #962 

Removing the page title in the content will be a tedious task.

### Full changelog

* Edit ```/layouts/_docs.html```

### Issues resolved

Fix #962 

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation 
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by tingaloo** [comment]
Whoops, misinterpreted the ticket. Putting the components back.

screen shot 2018-10-22 at 14 20 12

**Comment by coopr** [comment]
Running `npm start` locally fails to start the site, reports an error:

```
$ npm start

> docs.konghq.com@1.0.0 prestart /Users/cooper/Documents/GitHub/docs.konghq.com
> npm test


> docs.konghq.com@1.0.0 test /Users/cooper/Documents/GitHub/docs.konghq.com
> standard && echint --verbose

Error: 1 file(s) did not pass EditorConfig validation
  app/_layouts/docs.html:31 Expected an indentation at 12 instead of at 11.
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docs.konghq.com@1.0.0 prestart: `npm test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the docs.konghq.com@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cooper/.npm/_logs/2018-10-22T19_58_40_097Z-debug.log
```

**Comment by coopr** [comment]
LGTM! I'd like to have one more set of eyes on this...

**Comment by tingaloo** [comment]
That's right, just a little duplication that is spread across all docs.

**Comment by coopr** [comment]
I'm working now on cleaning up duplicate titles, and some other related tweaks - I'll add those to this PR soon.

One thing I just noticed on http://localhost:3000/0.14.x/plugin-development/custom-logic/ is:

plugin_development_-_implementing_custom_logic_-_v0_14_x___kong_-_open-source_api_management_and_microservice_management

**Comment by coopr** [comment]
I'm planning on leaving this open for a few days in hope that someone fixes the overlapping issue noted in https://github.com/Kong/docs.konghq.com/pull/968#issuecomment-432020671 - if that fix doesn't arrive soon, I'll merge and deploy this anyway.

**Comment by tingaloo** [comment]
screen shot 2018-10-23 at 18 34 48
screen shot 2018-10-23 at 18 34 55

By setting width to 50% it looks like so.

**Comment by adamjkuhn** [comment]
I've limited the width of of the heading and fixed the width of the search bar, stacking on tablet/mobile- LMK if this works or if you feel we should move the search/etc above the text
(https://puu.sh/BQgQ2/e73d6f7792.gif)

**Comment by coopr** [comment]
Great work @tingaloo @adamjkuhn - we'll ship this now, and likely make further tweaks to the header later.

**Pull request merged**
