### PR TITLE
feat: add KIC v2.0.x

### PR DESCRIPTION
**Pull request by rainest**
Continuation of #3081 

### Summary

This PR adds the upcoming (currently in alpha, soon to be beta) Kong Kubernetes Ingress Controller (KIC) `v2.0.x` documentation.

### Reason

New KIC BETA release is inbound, currently intended to be released within the next few days.

Supports https://github.com/Kong/kubernetes-ingress-controller/issues/1095
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1652
Resolves https://github.com/Kong/kubernetes-ingress-controller/issues/1674
Resolves https://github.com/Kong/docs.konghq.com/issues/2903
Resolves https://github.com/Kong/docs.konghq.com/issues/2904

### Testing

All new content was tested explicitly by me, and implicitly by the new [test suite](https://github.com/Kong/kubernetes-ingress-controller/tree/main/test/integration).

### Notes

I specifically seeded all the previous documentation from `v1.3.x` as the foundation for `v2.0.x` in 4149c096872611eea9a5accf217140ae32169eca, was this the right way to do things?

Question: how do I flag this release as beta/preview in these docs?

### CODE REVIEW

**Comment by lena-larionova** [comment]
TBA: waiting for branch deploy URL, will replace the autogenerated one when that's done.

**Comment by lena-larionova** [comment]
> I specifically seeded all the previous documentation from v1.3.x as the foundation for v2.0.x in 4149c09, was this the right way to do things?

This is definitely the way to go.

> how do I flag this release as beta/preview in these docs?

Working on it. We don't have a structure for this, so we're figuring it out as we go.

**Comment by lena-larionova** [comment]
@rainest @shaneutt added labels/metadata to the version dropdown and a banner for the 2.0.x docs:
 https://kic-v2-beta--kongdocs.netlify.app/kubernetes-ingress-controller/

**Comment by mflendrich** [comment]
Thank you @lena-larionova!

> Can you add this link anywhere that might be useful for users testing the beta? Might be good to put it in the KIC repo README temporarily, or the changelog, etc.

https://github.com/Kong/kubernetes-ingress-controller/pull/1706

**Pull request merged**
