### PR TITLE
fix(saml): adjust priority to 1010

### PR DESCRIPTION
**Pull request by tzssangglass**
### Description

 

sister PR: https://github.com/Kong/kong-ee/pull/7267

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by windmgc — APPROVED** [review]

**Comment by mheap** [comment]
Comment to @Kong/team-docs: This include needs an `if_version` tag one the change is released. The old priority was `900`, and the new one is `1010`. Each version of Gateway should show the correct priority

**Comment by tzssangglass** [comment]
ping this

**Comment by lena-larionova** [comment]
@mheap the renderer doesn't seem to want to display `if_version` correctly in the tables here. I always end up with either a break in the table (ie, breaks into two tables), or the entry appears on the same line as the previous.

Screenshot 2024-01-23 at 3 32 04 PM

Screenshot 2024-01-23 at 3 34 07 PM

Screenshot 2024-01-23 at 3 34 14 PM


I don't know which combination of things is messing with it: is it the tabs? The fact that this is an include? 

I've tried a bunch of approaches, none of these have worked:
* using `inline:true`
* leaving newlines around the table rows
* leaving no space
* leaving a newline either before or after the row
* using `{%- if_version -%}` syntax, with or without `inline:true`

**Comment by fabianrbz** [comment]
@lena-larionova I _think_ something like this should work (versions might be wrong though)
```
saml                        | {% if_version lte:3.4.x inline: true %} 900 {% endif_version %}{% if_version gte:3.5.x inline: true %} 1010 {% endif_version %}
```

**Comment by lena-larionova** [comment]
> @lena-larionova I _think_ something like this should work (versions might be wrong though)
> 
> ```
> saml                        | {% if_version lte:3.4.x inline: true %} 900 {% endif_version %}{% if_version gte:3.5.x inline: true %} 1010 {% endif_version %}
> ```

I thought about that - that _would_ work in most situations, but in this case the table row needs to move (ie be in two different positions for different versions), since the rows are in descending order.

**Comment by fabianrbz** [comment]
🤦 I'll give it another shot

**Comment by fabianrbz** [comment]
closing this one, this should be fixed  by #6866

**Pull request closed without merging**
