### PR TITLE
Removed "Back to Top" Links

### PR DESCRIPTION
**Pull request by Sayanta66**
Removed all of the "Back to Top" links from the document

Issue #3156 

### Review

@reviewer

### CODE REVIEW

**Comment by Sayanta66** [comment]
I have opened another PR which will close this issue completely. So, closing this PR

**Comment by falondarville** [comment]
Hi @Sayanta66, due to the format stripping in PR [#3208](https://github.com/Kong/docs.konghq.com/pull/3208) we are _unable_ to accept that PR. By format stripping, I mean that it looks like your code editor removed our line breaks and they are important for our formatting. The longer lines make it more difficult for us (and GitHub) to diff. 

If you open this PR back up (3207), we can merge it! Thank you for your time on this!

**Comment by Sayanta66** [comment]
@falondarville I opened it. It has all the back to top links removed...merge it....then I will do the copy-editing once more

**Comment by falondarville** [comment]
> @falondarville I opened it. It has all the back to top links removed...merge it....then I will do the copy-editing once more

Thank you, @Sayanta66 !

**Review by falondarville — APPROVED** [review]
LGTM

**Pull request merged**
