### PR TITLE
docs(mesh): fix bar for 2.8 release and add for 2.9

### PR DESCRIPTION
**Pull request by lukidzi**
### Description

Fix link to released bar 2.8.x and add a new one
### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [ ] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

### CODE REVIEW

**Comment by lukidzi** [comment]
Should works after kuma docs submodul update

**Comment by lena-larionova** [comment]
@lukidzi is there another submodule update that you're waiting on? We don't currently have any other PRs open.

**Comment by lukidzi** [comment]
Hi. I think for this one https://github.com/Kong/docs.konghq.com/pull/7582

**Review by lena-larionova — APPROVED** [review]
LGTM, you can ignore the failed smoke test, it doesn't work on forks.

**Pull request merged**
