### PR TITLE
Fix badges styles

### PR DESCRIPTION
**Pull request by fabianrbz**
### Description

What did you change and why?
 
Fix bages for non-plugin docs

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by lena-larionova** [comment]
@fabianrbz That seems to have fixed it for page titles: https://deploy-preview-5580--kongdocs.netlify.app/gateway/latest/kong-enterprise/dev-portal/customize/alternate-openapi-renderer/

But still looks odd when inline with a header: 
https://deploy-preview-5580--kongdocs.netlify.app/gateway/latest/admin-api/#upstream-object/

**Review by Guaris — APPROVED** [review]

**Comment by Guaris** [comment]
Titles
image

Inline with header
image

**Review by Guaris — APPROVED** [review]
This LGTM but i'll let @lena-larionova be the merger here.

**Comment by fabianrbz** [comment]
@Guaris is the title a screenshot of  [this](https://deploy-preview-5580--kongdocs.netlify.app/gateway/latest/admin-api/workspaces/reference/) page in the preview app?

This is what I see it

Screenshot 2023-05-16 at 22 09 18

**Comment by Guaris** [comment]
Ah yeah I see this too
image

**Comment by fabianrbz** [comment]
ok cool, then we are good :)

**Comment by lena-larionova** [comment]
One more small adjustment, fixing this:
Screenshot 2023-05-17 at 10 56 43 AM

To make it this:
Screenshot 2023-05-17 at 10 56 59 AM

**Pull request merged**
