### PR TITLE
Disable robots.txt on non-main deploys

### PR DESCRIPTION
**Pull request by mheap**
### Summary
Some deploy previews are being indexed by Google. This PR will adds a `disallow` rule to `robots.txt` to stop all search engines indexing the content unless `JEKYLL_ENV` is set to `production` (done via `netlify.toml`)

### Reason

Deploy previews are being indexed, we'd like them not to be:

https://master--kongdocs.netlify.app/enterprise/1.3-x/kong-for-kubernetes/install/
https://marcoam-patch-3--kongdocs.netlify.app/enterprise/2.1.x/kong-for-kubernetes/install-on-kubernetes/

### Testing
Visit `/robots.txt` in a deploy preview and it should contain the following:

```
User-agent: *
Disallow: /
```

Visit it in production and it should contain:

```
User-agent: *
Disallow: /enterprise/*
Disallow: /mesh/1.0*
Disallow: /mesh/1.1*
Disallow: /mesh/1.2*
Disallow: /gateway-oss/*
Disallow: /kubernetes-ingress-controller/1.0*
Disallow: /kubernetes-ingress-controller/1.1*
Disallow: /kubernetes-ingress-controller/1.2*
Disallow: /getting-started-guide/*
Disallow: /deck/pre-1.7*
Disallow: /deck/1.7*

Sitemap: {{site.links.web}}/sitemap.xml
```

### CODE REVIEW

**Comment by lena-larionova** [comment]
Looks like it worked in the deploy preview: https://deploy-preview-3437--kongdocs.netlify.app/robots.txt

**Review by lena-larionova — APPROVED** [review]
LGTM, thanks for doing this!

**Comment by mheap** [comment]
If you approve I can merge and test production tomorrow morning and revert
if needed. It should work based on my local tests setting JEKYLL_ENV

**Comment by mheap** [comment]
Works on `main` too https://docs.konghq.com/robots.txt

**Pull request merged**
