### PR TITLE
feat(portal): add guide for configuring Auth0 SSO for dev portal

### PR DESCRIPTION
**Pull request by Mierenga**
### Description

There was no existing guide for configuring Auth0 SSO in Konnect Dev Portal, just Azure.

This documents the quirks of the Auth0 integration and describes how to configure Konnect and Auth0.
 

### Testing instructions

Preview link: 

### Checklist 

- [ ] Review label added 
- [ ] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

### CODE REVIEW

**Comment by Mierenga** [comment]
@Kong/docs-maintainers do I have to add a term to https://github.com/Kong/docs.konghq.com/blob/main/.github/styles/kong/dictionary.txt to exclude it from Vale linting failures like
```
{"message": "[kong.Spelling] Did you really mean 'konnect_transform_updated_at_integer'?", "location": {"path": "app/konnect/dev-portal/access-and-approval/auth0.md", "range": {"start": {"line": 50, "column": 40}}}, "severity": "ERROR"}
```
https://github.com/Kong/docs.konghq.com/actions/runs/9783006288/job/27010610528?pr=7612#step:4:52

**Review by HenriPro — APPROVED** [review]
LGTM

**Comment by cloudjumpercat** [comment]
@Mierenga Hi! Thanks for creating that PR! I'm planning to take a look at that this week along with general Dev Portal SSO doc updates, so I might cherry pick your PR into a bigger Dev Portal SSO PR (I'll tag you on that :slightly_smiling_face: )

**Comment by cloudjumpercat** [comment]
@Mierenga I added this info to my Dev Portal SSO one pager PR #7633, so I'll close this PR out for now! Thank you so much for writing this up! I'll keep you updated when the other PR is ready for a tech review!

**Pull request closed without merging**
