### PR TITLE
Update kong.tracing.md

### PR DESCRIPTION
**Pull request by hasit**
Fix typos and add punctuations.

### Description

What did you change and why?
 
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.

### Testing instructions

Netlify link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by lena-larionova** [comment]
@hasit thanks for your contribution! However, for the PDK docs in particular, the source for all of this is in the `kong/kong` repo. For tracing, it's this file: https://github.com/Kong/kong/blob/master/kong/pdk/tracing.lua.

We generate docs directly from that file.
Can you please make your changes in the source instead?

**Comment by hasit** [comment]
Oh, thank you for pointing that out. I will make those changes and push them.

**Comment by hasit** [comment]
Closing this PR in favor of the autogen one.

**Comment by hasit** [comment]
@lena-larionova opened a PR - https://github.com/Kong/kong/pull/11262

**Pull request closed without merging**
