### PR TITLE
Release: Gateway 3.4.3.5 

### PR DESCRIPTION
**Pull request by acgoldsmith**
### Description

Sourced from https://github.com/Kong/kong-ee/blob/next/3.4.x.x/changelog/3.4.3.5/3.4.3.5.md

Addresses https://konghq.atlassian.net/browse/DOCU-3719 and https://konghq.atlassian.net/browse/DOCU-3713.

### Testing instructions

Preview link: 
https://deploy-preview-7076--kongdocs.netlify.app/gateway/changelog/#3435
https://deploy-preview-7076--kongdocs.netlify.app/gateway/latest/breaking-changes/34x/#tls-changes

### Checklist 

- [x] Review label added 
- [x] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins). 

Use any of the following keys:
* `gte:<version>` - greater than or equal to a specific version
* `lte:<version>` - less than or equal to a specific version
* `eq:<version>` - exactly equal to a specific version

You can do the same for older versions.

### CODE REVIEW

**Comment by acgoldsmith** [comment]
Note for Docs Reviewer:

Asked for clarification on two items on https://github.com/Kong/kong-ee/pull/8443, and noted with comments, so please skip those in your review. The question about where TLS content belongs will impact the breaking changes page as well, but planning to copy the content already published for https://docs.konghq.com/gateway/latest/breaking-changes/#tls-changes

**Review by lena-larionova — COMMENTED** [review]
Partial review, will implement the rest directly.

**Comment by lena-larionova** [comment]
Please ignore vale, it's doing that thing again where it randomly triggers on text `in backticks`.

**Comment by lena-larionova** [comment]
This PR is also:
* Adding all of the features that are in 3.4 that are also in either 3.5 or 3.6 already (no new docs, only adjusting version conditionals)
* Generating 3.4 kong.conf and splitting the kong.conf files into maintainable separate versions
  * This is a lot of added lines, I know. But we decided as a team that this is a more maintainable way to handle generated docs, and for this release, it's less work for me to split them than to try and figure out where the diffs are between each version.

**Review by lena-larionova — APPROVED** [review]

**Pull request merged**
