### PR TITLE
Set max-width to 1280px

### PR DESCRIPTION
**Pull request by fabianrbz**
### Description

Set max-width to 1280px to the topnav + content

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [ ] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

For example, if this change is for an upcoming 3.6 release, enclose your content in `{% if_version gte:3.6.x %} <content> {% endif_version %}` tags (or `if_plugin_version` tags for plugins). 

Use any of the following keys:
* `gte:<version>` - greater than or equal to a specific version
* `lte:<version>` - less than or equal to a specific version
* `eq:<version>` - exactly equal to a specific version

You can do the same for older versions.

### CODE REVIEW

**Comment by mheap** [comment]
Header could use some left/right padding

CleanShot 2024-04-11 at 12 08 25

Otherwise LGTM

**Comment by mheap** [comment]
I think it needs a bit more padding. Maybe 16 or 24px. (I feel like that customer that says "move it 3 pixels to the right")

8px (current)

CleanShot 2024-04-11 at 13 59 08

---

16px
CleanShot 2024-04-11 at 13 58 44

---

24px

CleanShot 2024-04-11 at 13 58 15

**Comment by fabianrbz** [comment]
the main problem with 1920px is with the home page, that konnect card looks odd :/

https://github.com/Kong/docs.konghq.com/assets/715229/05848dcc-2113-4a90-bf83-31676c7b1b43

**Comment by fabianrbz** [comment]
1280px 

https://github.com/Kong/docs.konghq.com/assets/715229/ea727d63-ae24-4d5c-aa05-9376071434c3

**Comment by fabianrbz** [comment]
I'll adjust it so that the content on landing pages is set to 1280px.

**Comment by fabianrbz** [comment]
I've updated it so that the landing pages have their content set to a max-width: 1280px and the rest of the pages 1920px;
Screenshot 2024-04-12 at 08 49 38
Screenshot 2024-04-12 at 08 49 31

**Review by Guaris — APPROVED** [review]

**Pull request merged**
