### PR TITLE
cleanup(mesh): remove old versions

### PR DESCRIPTION
**Pull request by lahabana**
### Description

The mesh docs experienced a lot of changes before 2.2.x
Maintaining all this is very combursome and all these versions
are now deprecated.

This simply removes old versions and makes the Mesh docs easier to
manage

We will still need to remove some of the conditional rendering but I'll
do this as a follow up PR

Part of https://github.com/kumahq/kuma-website/issues/2072

Signed-off-by: Charly Molter <charly.molter@konghq.com>

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

### CODE REVIEW

**Comment by mheap** [comment]
CleanShot 2024-11-28 at 15 59 14

Is maintenance the primary motivation here? I see that we're keeping 2.3-2.5, which are also out of support

**Review by mheap — APPROVED** [review]

**Comment by mheap** [comment]
Approving - if we get questions about where these docs went we may need to migrate to an archive site

**Comment by lahabana** [comment]
@fabianrbz @mheap is this failing because I opened the PR from a fork?

**Comment by lahabana** [comment]
Should I reopen the PR not from a fork or merge without it?

**Pull request closed without merging**
