### PR TITLE
Fix akward formatting in tables in Hub pages

### LINKED ISSUE #906: Sub-optimal formatting in tables in Hub pages
### Summary

Tables in the Markdown section of Hub pages have strange formatting. See the `Create a PASETO credential` section of https://docs.konghq.com/hub/peter-evans/paseto/

paseto_plugin___kong

### PR DESCRIPTION
**Pull request by dagolinuxoid**
### Summary
I edited markdown in order to render tables appropriately 

### Full changelog

* Removed some pipes `|` and spaces to make tables looks good

### Issues resolved

Fix #906

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [ ] Documentation 
- [ ] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by coopr** [comment]
Originally I thought that #906 was about CSS formatting in tables on hub pages.

Now that I've looked around more carefully, what I see that the problem is simpler - it is just that the tables on https://docs.konghq.com/hub/peter-evans/paseto/ don't use the same markdown formatting as the rest of the tables in the docs site.

So, I believe the correct fix for #906 is not CSS, but rather adjusting the table code on https://github.com/Kong/docs.konghq.com/blob/master/app/_hub/peter-evans/paseto/index.md to match the way tables are coded elsewhere, like on https://github.com/Kong/docs.konghq.com/blob/master/app/_hub/kong-inc/basic-auth/index.md 
  
Could you try that out?

**Comment by coopr** [comment]
Nice progress @dagolinuxoid 

I'd like the text in the tables to be aligned the same as text in other tables - when I run your PR locally, the PASETO tables look like this:

paseto_plugin___kong

As an example of what tables should look like, see https://docs.konghq.com/hub/kong-inc/hmac-auth/#signature-parameters 

hmac_authentication_plugin___kong

Note that the images in your previous comment don't look like the tables as rendered in the Docs website - you may want to run your branch locally to see the effects of the changes you are making - thanks!

**Comment by dagolinuxoid** [comment]
@coopr it should make the trick. If for some strange reasons it's not I'll  take a look at it later and deploy the Jekyllish site locally because at the moment  it's 1:35AM in SF it's 3:35PM and I'm going to sleep soon zZZ

**Comment by coopr** [comment]
Wow we did it! Thanks @dagolinuxoid much appreciated - go Hacktoberfest 🎃 !

**Pull request merged**
