### PR TITLE
Docs/oauth2 token management

### LINKED ISSUE #513: Documentation for /oauth_tokens
https://github.com/Mashape/kong/issues/483#issuecomment-174046454 says that it is implemented, and it is, but it is nowhere to be found in the docs.

### PR DESCRIPTION
**Pull request by rainest**
### Summary

Add description of GET and DELETE actions for the /oauth2_tokens endpoint

### Issues resolved

Fix #513 

### Checklist:
- [x] [Commit message & atomicity](https://github.com/Kong/getkong.org/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation N/A
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by thibaultcha** [comment]
@rainest Would you mind combining https://github.com/Kong/getkong.org/commit/965d9349accabab9ccffdd24b3fcbbded65762ba in this PR as well? This way we can close this and remove that stale branch (which is still valuable).

**Comment by coopr** [comment]
@rainest are you able to do what Thibault suggested? TIA!

**Comment by rainest** [comment]
Changes from 965d934 added.

**Comment by levfishbluefish** [comment]
Updated to move to the Plugins page, should be GTG now

**Pull request merged**
