### PR TITLE
fix(request-validator): content-type breaking change

### PR DESCRIPTION
**Pull request by vm-001**
### Description

What did you change and why?
 
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.

### Testing instructions

Netlify link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by vm-001** [comment]
I would like to apply this change only to PR gateway 2.8.x. But `release/gateway-2.8.x` doesn't exist. cc @lena-larionova

**Comment by lena-larionova** [comment]
@vm-001 

A few things:

1. When making changes to the docs repo, can you please make sure that your clone of the docs repo is up to date? This PR is pulling in changes that were merged for a previous release 2 months ago.
2. We don't have release branches for patch releases. We generally prep patches against `main`, and make sure that any additional docs PRs (like this one) aren't merged until the patch goes out.
3. Can you please link me to the related PR or FTI? At the moment, I don't see this change in the [changelog list for 2.8.4.0](https://konghq.atlassian.net/wiki/spaces/FTT/pages/2980118544/Kong+Enterprise+2.8.4.0), so I can't tell if it's actually supposed to be going into this release.

**Comment by lena-larionova** [comment]
Closing this PR, as the code change didn't get merged into the 2.8 release, and this branch is based on the wrong commit. Please open a new PR when you have some certainty that the code change is going in.

**Comment by vm-001** [comment]
@lena-larionova  new PR: https://github.com/Kong/docs.konghq.com/pull/5299

**Pull request closed without merging**
