### PR TITLE
docs: add KIC 2.5.x docs

### PR DESCRIPTION
**Pull request by pmalek**
### Summary

Add KIC 2.5.x docs

### Reason

In order to include information about https://github.com/Kong/kubernetes-ingress-controller/releases/tag/v2.5.0

### CODE REVIEW

**Comment by randmonkey** [comment]
Do we need to update 2.5 documents after the article is added? @rainest  [#4054](https://github.com/Kong/docs.konghq.com/issues/4054)

**Comment by cloudjumpercat** [comment]
@pmalek Your changes look good to me!

@randmonkey Based on the work in #4054 , do we just need to remove the "tech preview (alpha quality)" note at the top of [this page](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-gateway-api/) and the "Alpha limitations" section at the bottom? I'm just unsure what else needs to be completed before merging this PR.

**Comment by pmalek** [comment]
> @randmonkey Based on the work in #4054 , do we just need to remove the "tech preview (alpha quality)" note at the top of [this page](https://docs.konghq.com/kubernetes-ingress-controller/latest/guides/using-gateway-api/) and the "Alpha limitations" section at the bottom? I'm just unsure what else needs to be completed before merging this PR.

@cloudjumpercat I don't believe we should remove that just yet. As far as I understand Gateway APIs are still considered alpha feature in KIC.

cc: @Kong/team-k8s

**Comment by pmalek** [comment]
> I'm just unsure what else needs to be completed before merging this PR.

In my view this can be merged so that https://docs.konghq.com/kubernetes-ingress-controller/latest/ contains 2.5.x release and then we can amend them to include anything else that's worth mentioning (e.g. #4054 )

**Review by cloudjumpercat — APPROVED** [review]

**Comment by pmalek** [comment]
@cloudjumpercat Should we be worried about those smoke tests failing?

**Pull request merged**
