### PR TITLE
Collapsible subitems in sidebar navigation

### PR DESCRIPTION
**Pull request by wladimiiir**

### CODE REVIEW

**Comment by lena-larionova** [comment]
Some issues with whitespace at the end of longer titles:
Screen Shot 2020-05-19 at 1 37 50 PM
Screen Shot 2020-05-19 at 1 36 39 PM

**Comment by wladimiiir** [comment]
@lena-larionova I have adjusted the styling.

**Comment by lena-larionova** [comment]
@wladimiiir looks like the nav is no longer staying open when you've clicked on a nav entry. Hope I didn't mess something up in the merge?

**Comment by wladimiiir** [comment]
> @wladimiiir looks like the nav is no longer staying open when you've clicked on a nav entry. Hope I didn't mess something up in the merge?

I fixed the missing brackets after the merge. It should be working now.

**Pull request merged**
