### PR TITLE
Update apiVersion for ClusterIssuer to cert-manager.io/v1

### PR DESCRIPTION
**Pull request by avinashupadhya99**
### Summary
Update the apiVersion for ClusterIssuer from `cert-manager.io/v1alpha2` to `cert-manager.io/v1` as per https://cert-manager.io/docs/configuration/acme/dns01/route53/#creating-an-issuer-or-clusterissuer
### Reason
The apiVersion `cert-manager.io/v1alpha2` was not recognized when the _ClusterIssuer_ object is created.
image

### Testing
Follow the steps in https://docs.konghq.com/kubernetes-ingress-controller/1.3.x/guides/cert-manager/ except use `cert-manager.io/v1` as the apiVersion

### CODE REVIEW

**Comment by lena-larionova** [comment]
@Kong/team-k8s can you take a quick look?

**Review by rainest — CHANGES_REQUESTED** [review]
Ref https://cert-manager.io/docs/release-notes/release-notes-1.6/#legacy-cert-manager-api-versions-are-no-longer-served

Doesn't look like there's a clear break in older Kubernetes versions in [1.0](https://cert-manager.io/docs/release-notes/release-notes-1.0/) (the first version with v1), so I don't think we have any reason not to update these across the board.

@avinashupadhya99 there's an additional reference to `v1alpha2` after the example resource and a reference to `v1alpha1` in some example after, can you perform a find/replace to update them all to `v1` across the document?

We also just released 2.1, so you'll want to copy the updated doc from `app/kubernetes-ingress-controller/2.0.x/guides/cert-manager.md` to `app/kubernetes-ingress-controller/2.1.x/guides/cert-manager.md` (there were no 2.1 changes to that guide, it can be copied directly).

**Review by shaneutt — APPROVED** [review]

**Comment by shaneutt** [comment]
✔️ once travis' comment is resolved.

**Review by rainest — APPROVED** [review]

**Review by rainest — CHANGES_REQUESTED** [review]
Still the additional v1alpha2 after in the description: https://github.com/Kong/docs.konghq.com/blame/main/app/kubernetes-ingress-controller/2.1.x/guides/cert-manager.md#L185

**Comment by lena-larionova** [comment]
@rainest can you give it your final thumbs-up, if this looks good?

**Review by rainest — CHANGES_REQUESTED** [review]
@avinashupadhya99 we do still want that additional clause, just with the version updated to match the rest, so:

```
*Note*: If you run into issues configuring this,
be sure that the group (`cert-manager.io`) and
version (`v1alpha2`) match those in the output of
`kubectl describe crd clusterissuer`.
This directs cert-manager which CA authority to use to issue the certificate.
```
should become:

```
*Note*: If you run into issues configuring this,
be sure that the group (`cert-manager.io`) and
version (`v1`) match those in the output of
`kubectl describe crd clusterissuer`.
This directs cert-manager which CA authority to use to issue the certificate.
```

**Comment by avinashupadhya99** [comment]
My bad, fixed it!

**Review by rainest — APPROVED** [review]

**Review by lena-larionova — APPROVED** [review]

**Pull request merged**
