### PR TITLE
Improve Bitnami information for Kong in Azure

### PR DESCRIPTION
**Pull request by beltran-rubo**
### Summary

Improve Bitnami information for Azure Kong Single-VM and Cluster solutions.

### CODE REVIEW

**Comment by coopr** [comment]
Nice tune-up, thanks @beltran-rubo 

So, given that this page is now all about Bitnami's solutions, can I suggest you move it from "Made by: Tom Kerkhove" to "Made by: Bitnami"?

microsoft_azure_integration___kong

@tomkerkhove would you be OK with that?

**Comment by tomkerkhove** [comment]
The idea for the Azure page is to have one central landing page for Azure. 

My suggestion would be to keep it like this or create a Bitnami page (ie `Running Kong on Azure with Bitnami`) and add a pointer here.

Would that make sense?

**Comment by beltran-rubo** [comment]
We are fine with any of those suggestions, @coopr let us know the best approach for you.

**Comment by tomkerkhove** [comment]
To be clear - I'm not trying to keep the content under my own name, I just want to provide an umbrella for all things Azure with pointers to resources to run Kong on Azure.

Moving this content to a dedicated page is fine for me as it makes perfect sense - I'd prefer to keep my page in.

**Comment by coopr** [comment]
Right now, given the structure of https://docs.konghq.com/hub/, we need to have each Hub listing that is maintained by a different party on a different page. Thus, if @tomkerkhove maintains the Azure + Kong "integration" that is documented on https://docs.konghq.com/hub/tomkerkhove/microsoft_azure_container_instances/ , and if @beltran-rubo and Bitnami maintain the "integration" that is documented on https://docs.konghq.com/hub/tomkerkhove/microsoft_azure/, it would make sense for the former page to be "supported" and maintained by @tomkerkhove and the latter page to be "supported" and maintained by Bitnami staff.

Does that make sense to all of you?

Someday, yes, I agree that Kong Inc. would like to have one or more tiles on https://konghq.com/install/ pointing to Azure installation options. We had those briefly, but there were some questions internally about mixing Kong-supported and Community-supported options on https://konghq.com/install/ so we took them down until we work out those questions. 

Until then, let's focus on making these two Azure-related pages on https://docs.konghq.com/hub/ better.

**Comment by tomkerkhove** [comment]
I agree @coopr 	but the reason why I have https://docs.konghq.com/hub/tomkerkhove/microsoft_azure/ is to act as a landing page where you can find everything to run Kong on Azure. Currently, it has 2 Bitnami templates in `Deploying Kong via the Azure Marketplace` but (hopefully) there will be more in the future.

That's why I would suggest to have:
- ACI - https://docs.konghq.com/hub/tomkerkhove/microsoft_azure_container_instances/
- Kong with Bitnami - https://docs.konghq.com/hub/bitnami/microsoft_azure/
- Azure in general - https://docs.konghq.com/hub/tomkerkhove/microsoft_azure/

In that respect I would do a follow-up PR to move `Running PostgreSQL on Azure with Azure Database for PostgreSQL` & `Running Cassandra on Azure with Azure Cosmos Db` from https://docs.konghq.com/hub/tomkerkhove/microsoft_azure_container_instances/ to https://docs.konghq.com/hub/tomkerkhove/microsoft_azure/ as I'll need this for other services such as Service Fabric Mesh.

**Comment by coopr** [comment]
Ah, ok, let's try that @tomkerkhove ! Thanks for your contributions on this.

**Comment by tomkerkhove** [comment]
@coopr 	Awesome, I've created a seperate PR for this (#1049) but it can wait until this one has been merged in.

@beltran-rubo Feel free to let me know if you want me to jump in and help split these pages.

**Comment by beltran-rubo** [comment]
Lets close this one and work in your PR. Could you please create the new schema? I will be happy to fill the Bitnami ones.

**Pull request merged**
