### PR TITLE
Remove what's new in 1.3.x page from 1.5.x dev portal

### PR DESCRIPTION
**Pull request by tlblessing**
https://konghq.atlassian.net/browse/DOCS-1040

@lena-larionova can you please give me guidance on any needed redirect?

Direct link for review:

https://deploy-preview-2011--kongdocs.netlify.app/enterprise/1.5.x/developer-portal/

1.3 Overview entry is no longer present in Dev Portal doc.

### CODE REVIEW

**Comment by lena-larionova** [comment]
Since you're removing the page, you'll need to add a `redirect_from` to the front matter of some other page in the docs. 

The format is: `redirect_from: "<relative path to old doc page>" `
eg: `redirect_from: "/enterprise/1.5.x/developer-portal/administration/applications" `

See the application registration page for an example of this in use: https://github.com/Kong/docs.konghq.com/blob/master/app/enterprise/1.5.x/developer-portal/administration/application-registration.md

**Comment by tlblessing** [comment]
> Since you're removing the page, you'll need to add a `redirect_from` to the front matter of some other page in the docs.
> 
> The format is: `redirect_from: "<relative path to old doc page>" `
> eg: `redirect_from: "/enterprise/1.5.x/developer-portal/administration/applications" `
> 
> See the application registration page for an example of this in use: https://github.com/Kong/docs.konghq.com/blob/master/app/enterprise/1.5.x/developer-portal/administration/application-registration.md

As we discussed, this is a nav only (that I didn't know about) issue. Thanks for your guidance!

**Comment by tlblessing** [comment]
image
Need to investigate broken links. Saw a bunch in earlier builds but they weren't related to this ticket.

**Comment by lena-larionova** [comment]
> As we discussed, this is a nav only (that I didn't know about) issue. Thanks for your guidance!
@tlblessing you definitely still need a redirect once you remove the old topic from the nav. That will fix your broken links as well.

**Comment by tlblessing** [comment]
> > As we discussed, this is a nav only (that I didn't know about) issue. Thanks for your guidance!
> 
> @tlblessing you definitely still need a redirect once you remove the old topic from the nav. That will fix your broken links as well.

@lena-larionova ok I made a few attempts to do a redirect to no avail. I have only done redirects in an .htaccess file or with Drupal redirect module. Can you please assist me with this? What am I doing wrong? I'll write it up on the wiki for future writers who are also not familiar with redirects in md.

**Comment by lena-larionova** [comment]
I think you're missing the indents. Here's what worked for me:
image

**Comment by tlblessing** [comment]
> I think you're missing the indents. Here's what worked for me:
> 
> Screen Shot 2020-05-08 at 10 43 01 AM

@lena-larionova Yay, that worked! Thank you kindly. Ready for your review now.

**Pull request merged**
