### PR TITLE
Feat: Insomnia buttons for API catalog landing page

### PR DESCRIPTION
**Pull request by lena-larionova**
### Description

Adding Run in Insomnia buttons to API catalog in the docs.

### Testing instructions

Preview link: https://deploy-preview-6329--kongdocs.netlify.app/api/

Button alignment feels like the least bad one of the ones I've tried. 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by lena-larionova** [comment]
@fabianrbz not 100% sure to tell if I did this right - I _think_ this won't hurt/affect the spec pages themselves, but I'm sure how to test that. 

Also not entirely sure what the best alignment would be here.

**Comment by fabianrbz** [comment]
@lena-larionova That's alright, you can add anything you want to the frontmatter and it won't affect the OAS pages. The only important thing there is the product id.

I'm not sure about the alignment though, a few alternatives (not that I like them more :/ )
Screenshot 2023-10-18 at 10 11 31
Screenshot 2023-10-18 at 10 09 18
Screenshot 2023-10-18 at 10 15 44

**Comment by Guaris** [comment]
Screen Shot 2023-10-18 at 11 05 22 AM
What about this?

**Review by Guaris — APPROVED** [review]
LGTM -- I'll let you merge in case anyone else needs to look at it.

**Pull request merged**
