### PR TITLE
feat(support-tags) add protocol and run_on tags to Plugins WiP

### PR DESCRIPTION
**Pull request by adamjkuhn**
**NOTE**: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md

### Summary

Protocol tags (http/stream/stream + http) display in the hub cards:
screen shot 2018-11-07 at 2 09 49 pm

Both protocol and layer tags display on plugin detail page sidebar:
screen shot 2018-11-07 at 2 08 40 pm

### Full changelog

* edited hub_cards.html to conditionally include protocol tag
* edited extension.html to conditionally include both protocol and layer tags
* edited /hmac-auth/index.md as an initial example
* updated hub.css for card styles

### Checklist:

- [x ] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [ ] Documentation N/A 
- [x ] Spellchecked my updates
- [ ] Ready to be merged

### CODE REVIEW

**Comment by coopr** [comment]
@adamjkuhn I've added the new keys+values to the "fill in the blanks" page for new hub additions, I've moved the keys/values to the correct place, and I've added some more examples while we are testing.

**Comment by adamjkuhn** [comment]
@coopr I've updated the values to properly display both in the Hub cards and the plugin detail page sidebars, let me know if this requires further attention. I did remove the fixme comments under the assumption the three examples were properly tagged.

screen shot 2018-11-07 at 8 42 43 pm

**Comment by coopr** [comment]
It'd be good to leave in the FIXMEs in - as pretty much all of this needs a check-in Core and/or OCTO, and every plugin needs to be reviewed, before we ship this.

**Comment by adamjkuhn** [comment]
@coopr the FIXMEs are back- if anything else requires attention please let me know.

**Comment by coopr** [comment]
Updated to new `run_on` terminology.

**Comment by levfishbluefish** [comment]
@adamjkuhn is this still a valid change that needs to get merged in?

**Comment by adamjkuhn** [comment]
> @adamjkuhn is this still a valid change that needs to get merged in?

I think we can kill this, I believe it's no longer valid.

**Pull request closed without merging**
