### PR TITLE
Seo/add evergreen urls

### PR DESCRIPTION
**Pull request by mheap**
### Summary
SEO enhancements to help with SERP. This is a fairly involved change that needs a lot of manual testing, and ~some automated tests adding~ (automated tests now added).

Changes:

* Render a `/latest/` URL for each product that is versioned
* Set the canonical URL to `/latest/` for all versions
* If the current page does not have an equivalent URL on `/latest/`, set the canonical link to the latest version that _does_ have that URL
* If the page has a `rel=canonical` also set `robots=noindex`
* Build a sitemap that contains only the pages that are known to be canonical

### Testing
See review app

### CODE REVIEW

**Comment by lena-larionova** [comment]
Should the sitemap.xml file itself be in the sitemap? Currently, it is:

```
<url>
  <loc>https://docs.konghq.com/sitemap.xml</loc>
  <lastmod>2022-04-08T20:10:05+00:00</lastmod>
  <changefreq>weekly</changefreq>
  <priority>1.0</priority>
</url>
```

**Comment by mheap** [comment]
Good catch! I've just pushed a change that removes them both from the sitemap

**Comment by lena-larionova** [comment]
The plugin hub landing page (docs.konghq.com/hub) is linking to docs.konghq.com as its canonical:
https://deploy-preview-3810--kongdocs.netlify.app/hub/

```
<link rel="canonical" href="https://docs.konghq.com/">
```

**Comment by lena-larionova** [comment]
For the KIC landing page, any versions before latest link to 2.2.x as the canonical instead of `latest`. 

For example:

* Link: https://deploy-preview-3810--kongdocs.netlify.app/kubernetes-ingress-controller/
  
   Canonical URL: https://docs.konghq.com/kubernetes-ingress-controller/

* Link: https://deploy-preview-3810--kongdocs.netlify.app/kubernetes-ingress-controller/2.2.x/

   Canonical URL: https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/

* Link: https://deploy-preview-3810--kongdocs.netlify.app/kubernetes-ingress-controller/2.1.x/
   
   Canonical URL: https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/

**Comment by lena-larionova** [comment]
The Gateway and Mesh changelogs aren't being picked up by the sitemap, and aren't getting any canonicals generated:
https://deploy-preview-3810--kongdocs.netlify.app/gateway/changelog/
https://deploy-preview-3810--kongdocs.netlify.app/mesh/changelog/

They're rare cases, in that these files are in versioned products but aren't versioned themselves. Just looked through the directory, I don't think there are any other files in this situation.

**Comment by mheap** [comment]
Great catch on all of the above. I've added test cases for them all, and have resolved all of the issues

**Comment by lena-larionova** [comment]
Everything looks good, checked all the things again. Found only one issue: the `https://docs.konghq.com/hub/` URL doesn't appear in the sitemap. I don't think I checked that last time, sorry about that.

**Comment by mheap** [comment]
Fixed the issue with `/hub`.

I've noticed that the root `/gateway/`, `/mesh/` etc pages aren't listed either. I'll look at that next

**Review by lena-larionova — APPROVED** [review]
I think this is good now, unless there's something else here that I don't know to check for. Canonicals are generating as expected, sitemap looks good, nothing else stands out. LGTM!

**Pull request merged**
