### PR TITLE
Use Github Actions instead of Travis CI

### PR DESCRIPTION
**Pull request by nijikokun**
Speeds with Travis CI are slow due to the number of repositories utilizing it. Github actions is isolated per repository not organization. This should speed development up.

### CODE REVIEW

**Comment by nijikokun** [comment]
If the tests above do not pass will test using `-T` on the exec command. Seems it's a regression.

**Comment by nijikokun** [comment]
The previous test shows ❌ due to me cancelling the Travis CI build.

**Comment by h3xar0n** [comment]
@GayleNeumann , @hutchic , @connorckong --I am planning to approve and merge this tomorrow AM Pacific time. Please let me know if there are any questions or objections.

**Comment by nijikokun** [comment]
Tests are passing 🎉 

---

**Before Github Actions (Travis CI)**

1 hour 20 minutes

**After Github Actions**

14 minutes

**Pull request merged**
