### PR TITLE
chore: remove depracated performance document

### PR DESCRIPTION
**Pull request by jschmid1**
### Description

@fffonion @kikito I think this should be dropped from master (and 3.5) as this isn't maintained and used anymore

### Checklist 

- [x] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by lena-larionova** [comment]
@jschmid1 does this still work in previous versions, do you know?

**Comment by jschmid1** [comment]
It should, but we as a team moved away from it, so there is no maintenance anymore.

**Comment by fffonion** [comment]
I agree, let's move it from docs.

**Comment by lena-larionova** [comment]
Closing in favor of https://github.com/Kong/docs.konghq.com/pull/6452.

**Pull request closed without merging**
