### PR TITLE
Switch to mise for managing Ruby/Node versions

### PR DESCRIPTION
**Pull request by mheap**
### Description

Switch from `rbenv` to `mise` for tool installs in the installation instructions as it's easier to use + also supports node

### Testing instructions

Preview link: N/A

### Checklist 

- [x] Review label added 
- [x] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

### CODE REVIEW

**Comment by Guaris** [comment]
@mheap Without rbenv how do I address this error?
```
angel$ mise install
mise all runtimes are installed
```
Then 
```
angel$ make install
```
```
akefile:10: *** ruby "3.3.3" is required. Found "ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.x86_64-darwin22]". Run `rbenv install "3.3.3"`.  Stop.
```

**Comment by mheap** [comment]
@Guaris Did you add the mise activate line to your zshrc?

**Review by fabianrbz — APPROVED** [review]
LGTM ✨

**Comment by fabianrbz** [comment]
@Guaris try removing the [rbenv bits ](https://github.com/rbenv/rbenv?tab=readme-ov-file#shell-completions) from your `.zshrc` if you have any.

**Comment by Guaris** [comment]
Works for me @fabianrbz @mheap

**Pull request merged**
