### PR TITLE
docs(plugin) remove bug button

### PR DESCRIPTION
**Pull request by coopr**
### Summary

Remove un-used "Report bug" buttons from EE plugin docs

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/getkong.org/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [ ] Documentation N/A 
- [ ] Spellchecked my updates N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by thibaultcha** [comment]
If this property has been removed from all relevant places (and is thus unused as of now), it should also be removed from the template at `app/_includes/header.html`

**Comment by coopr** [comment]
@bungle in https://github.com/Kong/docs.konghq.com/pull/751 you add a new button type - you could, instead, re-use this pre-existing button - do you want to do so?

**Comment by bungle** [comment]
I can remove it in my PR too.

**Comment by bungle** [comment]
The `app/_includes/header.html` includes removal of this button in: #751 (these can be merged in any order, the release branch needs to be rebased on master though)

**Comment by thibaultcha** [comment]
> the release branch needs to be rebased on master though

Yep, figured out I would do that once all the opened PRs against 0.14.0 are merged anyway!

**Pull request merged**
