### PR TITLE
fix overlapping email form on /install pages

### LINKED ISSUE #1020: Overlapping email form on /install pages
Pages like https://docs.konghq.com/install/google-cloud/ have this problem:

install_-_google_cloud____kong_-_open-source_api_management_and_microservice_management

### PR DESCRIPTION
**Pull request by vyaspranjal33**
**NOTE**: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md

### Summary

added changes that will fix #1020 

### Full changelog

* [Edited docs to ...]
* [Added cool new feature ...]
* ...

### Issues resolved

Fix #1020 

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation 
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by vyaspranjal33** [comment]
@coopr  i've fixed issue #1022  but build is failing due to eslint

**Comment by vyaspranjal33** [comment]
@coopr  please review

**Comment by coopr** [comment]
Travis build fails - there is some error with this PR currently. You can see details of the error here https://travis-ci.org/Kong/docs.konghq.com/builds/450245862?utm_source=github_status&utm_medium=notification or is you run `npm start` locally.

**Comment by vyaspranjal33** [comment]
This PR can be merged

**Comment by coopr** [comment]
Sorry @vyaspranjal33 I cannot test, and certainly cannot merge, this PR until Travis tests pass - the details of the error are on https://travis-ci.org/Kong/docs.konghq.com/builds/450245862?utm_source=github_status&utm_medium=notification

At this point, I've provided you with the same trouble-shooting information twice. Please make an attempt to correct the error, and add the commit that does so to this PR.

**Comment by vyaspranjal33** [comment]
I will take care of it @coopr

**Comment by vyaspranjal33** [comment]
@coopr tests are passed and now this PR is ready as fix of #1020

**Comment by coopr** [comment]
When I build and run locally, I get some warnings, and a clearly broken website:

```
Coopers-Kong-MacBook-Pro:docs.konghq.com cooper$ npm start

> docs.konghq.com@1.0.0 prestart /Users/cooper/Documents/GitHub/docs.konghq.com
> npm test


> docs.konghq.com@1.0.0 test /Users/cooper/Documents/GitHub/docs.konghq.com
> standard && echint --verbose


> docs.konghq.com@1.0.0 start /Users/cooper/Documents/GitHub/docs.konghq.com
> gulp

[18:13:30] Using gulpfile ~/Documents/GitHub/docs.konghq.com/gulpfile.js
[18:13:30] Starting 'clean'...
[18:13:31] Finished 'clean' after 829 ms
[18:13:31] Starting 'default'...
[18:13:31] Starting 'javascripts'...
[18:13:32] Starting 'images'...
[18:13:32] Starting 'fonts'...
[18:13:36] all files 94.83 kB
[18:13:36] Finished 'javascripts' after 4.88 s
[18:13:39] all files 2.77 MB
[18:13:39] Finished 'fonts' after 6.7 s
[18:14:05] gulp-imagemin: Minified 122 images (saved 817 kB - 37.6%)
[18:14:05] all files 1.38 MB
[18:14:05] Finished 'images' after 32 s
[18:14:05] Starting 'build'...
[18:14:05] Starting 'jekyll'...
[18:14:53] Configuration file: jekyll.yml
            Source: app
       Destination: ./dist/
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 46.503 seconds.
 Auto-regeneration: disabled. Use --watch to enable.

[18:14:53]      Build Warning: Layout 'about' requested in about/advantages.md does not exist.
     Build Warning: Layout 'about' requested in about/benchmark.md does not exist.
     Build Warning: Layout 'about' requested in about/faq.md does not exist.
     Build Warning: Layout 'about' requested in about/index.md does not exist.
     Build Warning: Layout 'about' requested in about/pci-dss.md does not exist.
     Build Warning: Layout 'about' requested in about/who.md does not exist.

[18:14:53] Finished 'jekyll' after 48 s
[18:14:53] Starting 'html'...
[18:14:54] all files 38.53 MB
[18:14:54] Finished 'html' after 1.58 s
[18:14:54] Starting 'styles'...
[18:14:55] Plumber found unhandled error:
 Error in plugin "gulp-less"
Message:
    Unrecognised input. Possibly missing opening '{' in file /Users/cooper/Documents/GitHub/docs.konghq.com/app/_assets/stylesheets/pages/install-method.less line no. 174
Details:
    type: Parse
    filename: /Users/cooper/Documents/GitHub/docs.konghq.com/app/_assets/stylesheets/pages/install-method.less
    index: 3692
    line: 174
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: ,},
    lineNumber: 174
    fileName: /Users/cooper/Documents/GitHub/docs.konghq.com/app/_assets/stylesheets/pages/install-method.less

[18:14:55] Finished 'styles' after 982 ms
[18:14:55] Finished 'build' after 51 s
[18:14:55] Starting 'browser-sync'...
[18:14:55] Finished 'browser-sync' after 10 ms
[18:14:55] Starting 'copycss'...
[18:14:55] Finished 'copycss' after 767 μs
[18:14:55] Starting 'watch'...
[18:14:56] Finished 'watch' after 602 ms
[18:14:56] Finished 'default' after 1.4 min
[ ▶ ] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000
    External: http://192.168.130.12:3000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.130.12:3001
 ---------------------------------------
[ ▶ ] Serving files from: dist

```

documentation_for_kong_-_v0_14_x___kong_-_open-source_api_management_and_microservice_management_and_github_desktop_and_docs_konghq_com_ _gulp_ _npm_term_program_apple_terminal_term_xterm-256color_ _179x48_and_slack_-_kong_and_fix_overlappi

**Comment by vyaspranjal33** [comment]
I just removed corresponding lines n code from html file n style files i
haven't touch any other code 😅

**Comment by vyaspranjal33** [comment]
@coopr parse error solved build check passed now .less file is as it is with modified code for our issue #1020

**Comment by coopr** [comment]
When I run locally I still see broken styling:

documentation_for_kong_-_v0_14_x___kong_-_open-source_api_management_and_microservice_management_and_fix_overlapping_email_form_on__install_pages_by_vyaspranjal33_ _pull_request__1022_ _kong_docs_konghq_com


@vyaspranjal33 If I may give some frank feedback - you and I have been going back and forth on this for quite a while, and it doesn't really seem like we are making progress. I need to not keep testing changes of yours that don't actually solve the problem, and I'm guessing this must be getting a little frustrating. Can I suggest you close this PR for now? Then, later, if you think you've gained the skills and knowledge to fix this issue, or any other issue on this repo, you could open a new PR - what do you think? 

Please understand that we _really_ appreciate community contributions, and we welcome your help anytime!

**Comment by vyaspranjal33** [comment]
I agree please close

**Pull request closed without merging**
