### PR TITLE
docs(cors) add a config field: override_origins

### PR DESCRIPTION
**Pull request by WALL-E**
Introduced in Mashape/kong#2788

### CODE REVIEW

**Comment by coopr** [comment]
Thanks @WALL-E  - we've just made Kong Hub https://docs.konghq.com/hub/ live, which has caused some changes to the files you edited in this PR. Please reapply your changes to the new files you will now find at https://github.com/Kong/docs.konghq.com/tree/master/app/_hub/kong-inc

**Comment by WALL-E** [comment]
@coopr I updated it

**Comment by coopr** [comment]
Sorry @WALL-E I will clarify - your PR currently changes `app/plugins/cors.md`

It instead needs to update https://github.com/Kong/docs.konghq.com/blob/master/app/_hub/kong-inc/cors/index.md

**Comment by WALL-E** [comment]
@coopr  It's my mistake, I got it

**Comment by john-paul-keenan** [comment]
Just gave this a read and everything looks good to me 👍

**Comment by Bradamant3** [comment]
and another unsigned-for-years-CLA, safe to close.

**Pull request closed without merging**
