### PR TITLE
[DOCU-1062][DOCU-1776][DOCU-1784] Support matrix/compatibility guide v1

### PR DESCRIPTION
**Pull request by lena-larionova**
### Review
@PaulFischer-Kong , @falondarville 

### Summary
First version/MVP of a support matrix for Kong products/projects. The goal is to display the third-party platform and software configurations that are eligible for support under our subscription offerings. 

From Paul F:
Customers and OSS users can reference the page to determine which 3rd party software Kong Inc. maintains accurate product tests coverage, compatibility patches and support for. As an example, a customer/user might want to know that Kong Gateway 2.5 version supports a postgres database with version 13. 

### Reason
**Customer Experience team:** is requesting a support matrix to reduce the # of support inquiries received from customers who need help operating Kong 3rd party software which are "not supported". 
**Product/Eng team:** is needing a support matrix so we only spend eng resources on fixing issues with 3rd party software versions which we say are "supported" and tested. This effort sets good customer/user expectations and ensures we maintain high product quality.

### Testing
https://deploy-preview-3058--kongdocs.netlify.app/konnect-platform/compatibility/

### CODE REVIEW

**Review by falondarville — APPROVED** [review]
Looks awesome!!

**Comment by mheap** [comment]
image

Do we need these buttons, or could we trigger when the product/version is changed?

**Comment by lena-larionova** [comment]
> Do we need these buttons, or could we trigger when the product/version is changed?

Passing the idea by Paul F. Him and the various stakeholders can hash it out.

**Comment by lena-larionova** [comment]
> image
> 
> Do we need these buttons, or could we trigger when the product/version is changed?

Pulled this out into a separate ticket. Will look into an accessible & clean way to do this after the merge of the initial version of the compatibility guide.

**Pull request merged**
