### PR TITLE
docs(api): define ordering of audit log requests

### PR DESCRIPTION
**Pull request by nowNick**
### Description

Audit Log request were previously sorted by `request_id`. With the upcoming changes they'll be sorted by `request_timestamp` descending - which is from latest to oldest.

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

### CODE REVIEW

**Review by lena-larionova — APPROVED** [review]
@nowNick LGTM - do you plan on adding any other info, or is this PR ready for review/merge?

**Comment by nowNick** [comment]
Hey @lena-larionova !

I was hoping I could preview the change here: https://deploy-preview-7178--kongdocs.netlify.app/gateway/api/admin-ee/latest/#/audit-logs/get-audit-requests
but I think the conditional version tag is excluding it since the latest version there is 3.6.0.x and I'm allowing it only for: 
`{% if_version gte:3.7.x %}` 

Is that expected?

**Comment by lena-larionova** [comment]
Ah! I'm sorry, I didn't realize this was one of the migrated pages, that's my miss. You will actually have to update the spec instead now: https://github.com/Kong/docs.konghq.com/blob/main/api-specs/Gateway-EE/latest/kong-ee.yaml#L14781

**Comment by nowNick** [comment]
Got it! I'll fix that but for now I'll change this PR back to draft.

**Comment by nowNick** [comment]
@lena-larionova I've updated the spec but I still can't see it in deploy preview : https://deploy-preview-7178--kongdocs.netlify.app/gateway/api/admin-ee/latest/#/audit-logs
Shouldn't it be visible there? 🤔

**Comment by lena-larionova** [comment]
> @lena-larionova I've updated the spec but I still can't see it in deploy preview : https://deploy-preview-7178--kongdocs.netlify.app/gateway/api/admin-ee/latest/#/audit-logs Shouldn't it be visible there? 🤔

We have to upload the spec to the konnect dev portal, which is currently not automated. I'll upload it after this PR gets merged.

**Comment by lena-larionova** [comment]
Threw it into swagger editor to test, everything displays as it should. Will merge with 3.7.

**Comment by Guaris** [comment]
Pulled all of these changes into #7353 so they can be merged with the release of 3.7. Closing this PR.

**Pull request closed without merging**
