### PR TITLE
docs(secret-management) update secret management docs for GA

### PR DESCRIPTION
**Pull request by bungle**
### Summary

1. [docs(*) copy gateway/2.8.x docs to gateway/3.0.x](https://github.com/Kong/docs.konghq.com/commit/9b7b88451aa2ca5856bb7d8205706e8c750dc32a)
2. [docs(secret-management) update secret management docs for GA](https://github.com/Kong/docs.konghq.com/pull/4379/commits/85bbf82fb55fb975d8503b50c28bd089b5711685)

### CODE REVIEW

**Comment by lena-larionova** [comment]
@bungle The 3.0.x release docs are here: https://github.com/Kong/docs.konghq.com/tree/release/gateway-3.0/src/gateway

Please delete the app/gateway/3.0.x repository and make any updates you need in https://github.com/Kong/docs.konghq.com/tree/release/gateway-3.0/src/gateway/kong-enterprise/secrets-management/ instead.

**Comment by mheap** [comment]
I've applied @bungle's changes in the `src` directory and force pushed.

Things to note:

* The following change is incorrect and has not been applied: https://github.com/Kong/docs.konghq.com/commit/85bbf82fb55fb975d8503b50c28bd089b5711685#diff-1884a27065c5c7a49565441698cc492b27a4b26b39a2bb4e3d467ebd8c8fe101R52
* The section about Entity configuration seems to be missing from 3.0 - should we re-add it? https://github.com/Kong/docs.konghq.com/commit/85bbf82fb55fb975d8503b50c28bd089b5711685#diff-1884a27065c5c7a49565441698cc492b27a4b26b39a2bb4e3d467ebd8c8fe101R44

**Comment by lena-larionova** [comment]
Converted the links into hub-style. The `page.kong_version` variable doesn't work in `/hub/` docs, have to use `/latest/`.

**Comment by lena-larionova** [comment]
> * The section about Entity configuration seems to be missing from 3.0 - should we re-add it? [85bbf82#diff-1884a27065c5c7a49565441698cc492b27a4b26b39a2bb4e3d467ebd8c8fe101R44](https://github.com/Kong/docs.konghq.com/commit/85bbf82fb55fb975d8503b50c28bd089b5711685#diff-1884a27065c5c7a49565441698cc492b27a4b26b39a2bb4e3d467ebd8c8fe101R44)

Do you mean this phrasing? 

> If you're using 2.8.2 or below, and have not set `vaults_use_new_style_api=on` in `kong.conf` you will need to replace `/vaults/` with `/vaults-beta/` in the examples below.

I would say no, since the docs are versioned. This info is in the 2.8 docs.

**Pull request merged**
