### PR TITLE
Updated ingress declaration examples to match

### PR DESCRIPTION
**Pull request by geocomm-shenningsgard**
### Summary

The attributes defined for apiVersion: networking.k8s.io/v1 did not match the one defined for apiVersion: networking.k8s.io/v1beta1. I did my best as a kubernetes novice, but please have someone internal review my changes and make any others necessary.

### Reason

We're updating from k8s 1.21 to 1.22 and need these instructions to know exactly what to do wrt kong

### CODE REVIEW

**Comment by cloudjumpercat** [comment]
@Kong/team-k8s Hi! Could someone review the changes in this PR? Thanks!

**Review by rainest — APPROVED** [review]
:+1: nothin major, just makes the two examples use the same values, which they should.

**Comment by cloudjumpercat** [comment]
Thanks @rainest !

**Review by cloudjumpercat — APPROVED** [review]
LGTM!

**Pull request merged**
