### PR TITLE
[DOCS-1646] gRPC Web plugin add datatypes

### PR DESCRIPTION
**Pull request by tlblessing**
https://konghq.atlassian.net/browse/DOCS-1646 part of epic https://konghq.atlassian.net/browse/DOCS-1396.

Schema:

https://github.com/Kong/kong-plugin-grpc-web/blob/master/kong/plugins/grpc-web/schema.lua

Direct review link:

https://deploy-preview-2705--kongdocs.netlify.app/hub/kong-inc/grpc-web/

### CODE REVIEW

**Review by murillopaula — COMMENTED** [review]
https://deploy-preview-2705--kongdocs.netlify.app/hub/kong-inc/grpc-web/#parameters

vs

https://deploy-preview-2704--kongdocs.netlify.app/hub/kong-inc/correlation-id/#parameters

I see `config.routes.id` only. Does it mean that gRPC web can't be applied to services, plugins, consumers, etc? Only routes?

**Comment by tlblessing** [comment]
> https://deploy-preview-2705--kongdocs.netlify.app/hub/kong-inc/grpc-web/#parameters
> 
> vs
> 
> https://deploy-preview-2704--kongdocs.netlify.app/hub/kong-inc/correlation-id/#parameters
> 
> I see `config.routes.id` only. Does it mean that gRPC web can't be applied to services, plugins, consumers, etc? Only routes?

@murillopaula looks like only routes. grpc gateway is the same:

> params:
>   name: grpc-gateway
>   route_id: true

**Comment by murillopaula** [comment]
> https://deploy-preview-2705--kongdocs.netlify.app/hub/kong-inc/grpc-web/#parameters
>
> vs
>
> https://deploy-preview-2704--kongdocs.netlify.app/hub/kong-inc/correlation-id/#parameters
>
> I see config.routes.id only. Does it mean that gRPC web can't be applied to services, plugins, consumers, etc? Only routes?

@gszr what are your thoughts?

**Comment by gszr** [comment]
> > https://deploy-preview-2705--kongdocs.netlify.app/hub/kong-inc/grpc-web/#parameters
> > vs
> > https://deploy-preview-2704--kongdocs.netlify.app/hub/kong-inc/correlation-id/#parameters
> > I see config.routes.id only. Does it mean that gRPC web can't be applied to services, plugins, consumers, etc? Only routes?
> 
> @gszr what are your thoughts?

If memory serves me well, yes, it can only be applied to routes. @javierguerragiraldez is this assumption correct?

**Comment by javierguerragiraldez** [comment]
> If memory serves me well, yes, it can only be applied to routes. @javierguerragiraldez is this assumption correct?

I'd say yes, but mostly because i don't imagine what it would do if applied to a plugin or a service... even less a consumer

**Review by murillopaula — APPROVED** [review]

**Review by lena-larionova — APPROVED** [review]

**Pull request merged**
