### PR TITLE
[DOCU-2631] Update Mesh nav bar and move files

### PR DESCRIPTION
**Pull request by cloudjumpercat**
### Summary

- Reformatted content in the nav bar to match Kuma/Mesh IA plan
- Moved some files
- Added one file for a new doc

### Reason

DOCU-2631
### Testing

- Compare the nav in the Netlify/local preview to the spreadsheet (some things may have been moved around or slightly renamed based on feedback): https://docs.google.com/spreadsheets/d/1bdYIFK4RdoOGfunEd1txj8se9bR_6F55aoP3r52rDjc/edit#gid=1654209169
- Nav bar names might not always match the page title, this work will be done in later PRs.
- Verify that each sidebar nav item takes you to the correct page/doesn't error. 
- I reused all the icons from other docs, do they work here? Or should we come up with new ones?

### CODE REVIEW

**Comment by lena-larionova** [comment]
It looks like the main error is that a file is missing. Here's an excerpt from the netlify log linked above:

> `Could not find a source file at 'src//.repos/kuma/src/introduction/architecture.md' or src//.repos/kuma/src/introduction/architecture/index.md`

From what I can tell, there's no file named `architecture.md` anywhere. If you add that, the build should run fine.

**Comment by cloudjumpercat** [comment]
> It looks like the main error is that a file is missing. Here's an excerpt from the netlify log linked above:
> 
> > `Could not find a source file at 'src//.repos/kuma/src/introduction/architecture.md' or src//.repos/kuma/src/introduction/architecture/index.md`
> 
> From what I can tell, there's [no file named `architecture.md` anywhere](https://github.com/Kong/kuma-website-jekyll/tree/release/kuma-2.0/src/introduction). If you add that, the build should run fine.

@lena-larionova That's an expected error because the `.repos/kuma/` is a submodule where the docs are shared between repos. Merging in the Kuma nav PR in the Kuma repo should fix this error because I created/moved that file (and other shared files) in that PR. All shared content that both Kuma and Mesh use will "live" in the Kuma repo and be shared via the `.repos/kuma/` submodule.

**Review by lena-larionova — COMMENTED** [review]
Q: Is the navbar being generated from the Kuma navbar? That is, if we have copyedits to make, do they need to happen elsewhere, and not in this PR?

**Comment by mheap** [comment]
At this point the Kuma + Kong Mesh navbars have diverged enough that I would treat them as independent

**Comment by mheap** [comment]
Merging to enable people to fork from `release/mesh-2.0`. We can issue followup PRs as needed

**Pull request merged**
