### PR TITLE
Docs: describes new rate-limiting plugin ssl config options from PR #…

### PR DESCRIPTION
**Pull request by 27ascii**
### Summary

Document new redis ssl config options for rate-limiting plugin

- redis_ssl
- redis_ssl_verify
- redis_server_name

### Reason

PR https://github.com/Kong/kong/pull/6737 has introduced additional config options.

### CODE REVIEW

**Comment by lena-larionova** [comment]
@27ascii can you please update this branch based on latest changes in `release/gateway-2.7.x`? That will also force a preview to generate, as we've enabled it for the release branch now, and we can figure out what the error is (if there actually is one - it might just be flaky).

**Comment by 27ascii** [comment]
@lena-larionova I'm struggling with the rebase. I guess it would be easier to close this PR and I resubmit another one. What do you think?

**Comment by lena-larionova** [comment]
>  I'm struggling with the rebase. I guess it would be easier to close this PR and I resubmit another one. What do you think?

@27ascii That's probably a good idea. We're recently switched to this fork workflow instead of branching and I've run into the same issue as you 😅 . The simplest way to fix is just to make a new branch.

**Comment by 27ascii** [comment]
@lena-larionova I'll close this one and resubmit once https://github.com/Kong/docs.konghq.com/pull/3426 gets merged. Alternately you could just include the 3 config options in https://github.com/Kong/docs.konghq.com/pull/3426 too.

**Pull request closed without merging**
