### PR TITLE
Add link to `Catalog` to OAS pages

### PR DESCRIPTION
**Pull request by fabianrbz**
### Description

[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3581)

Add link to `Catalog` to OAS pages.

### Testing instructions

OAS pages now render a link back to the catalog

Preview link: 
* https://deploy-preview-6643--kongdocs.netlify.app/konnect/api/runtime-groups-configuration/latest/
* https://deploy-preview-6643--kongdocs.netlify.app/konnect/api/portal-rbac/latest/
* https://deploy-preview-6643--kongdocs.netlify.app/gateway/api/admin-ee/latest/

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by mheap** [comment]
The alignment of the `>` is off 
CleanShot 2023-12-11 at 14 01 09

I'd also expect to see the spec name next to `Catalog >` to show that it's breadcrumbs

**Comment by fabianrbz** [comment]
> The alignment of the `>` is off CleanShot 2023-12-11 at 14 01 09

weird, those are the default styles for that component 🤷 , I'll fix them.

> 
> I'd also expect to see the spec name next to `Catalog >` to show that it's breadcrumbs
good call, we just had the `Catalog` link in the dev portal.

**Comment by fabianrbz** [comment]
@mheap which browser is that?

**Comment by mheap** [comment]
Arc (Chrome based)

**Comment by fabianrbz** [comment]
Screenshot 2023-12-11 at 18 48 33

**Review by cloudjumpercat — APPROVED** [review]
LGTM! I'll let you merge this when you're ready

**Pull request merged**
