### PR TITLE
Dynatrace

### PR DESCRIPTION
**Pull request by ivan-gudak**
### Testing

review:general

### CODE REVIEW

**Comment by Guaris** [comment]
Is this for 3.1? @ivan-gudak

**Comment by Guaris** [comment]
@ivan-gudak Can you provide a description for this plugin?

**Comment by ivan-gudak** [comment]
> @ivan-gudak Can you provide a description for this plugin?
> Is this for 3.1? 

hello @Guaris ,
thank you for reviewing this.
Could you please suggest regarding the description - are you talking about changing the "description" field in _readme.md file? If you would like it here, in the comments, I'm providing this herein below.

What Dynatrace makes is not a plugin in the pure sense of this word. It's rather an integration.
To integrate with Dynatrace, we need the Prometheus plugin that exposes Kong Gateway metrics. Then we can scrape the metrics from Prometheus.
Schema-wise, it works like this:
  {KongGateway + PrometheusPlugin} => {Dynatrace OneAgent + Extension} => {DynatraceCluster}
or 
  {KongGateway + PrometheusPlugin} => {Dynatrace Operator (k8s)} => {DynatraceCluster}

Customers can see Kong Gateway metrics in their environment together.



Concerning 3.1 - yes, it will work with 3.1. We integrate via the Prometheus plugin, thus don't rely that much on the Kong Gateway version.

**Comment by Guaris** [comment]
@ivan-gudak could you please email the PM of plugins Gang Guo at [gang.guo@konghq.com](mailto:gang.guo@konghq.com) to discuss the specifics of this plugin?

**Comment by ivan-gudak** [comment]
> @ivan-gudak could you please email the PM of plugins Gang Guo to discuss the specifics of this plugin?

sure! Having a call with Gang Guo tomorrow afternoon.
Thank you again

**Comment by Guaris** [comment]
@ivan-gudak As I understand it your team will be building the plugin first. I'm going to close this PR for now, please re-open it whenever the Dynatrace plugin is ready!

**Pull request closed without merging**
