### PR TITLE
Copyedited the document

### PR DESCRIPTION
**Pull request by Sayanta66**
Copyedited the entire document. If this PR gets merged, then issue #3202 will get resolved.

### CODE REVIEW

**Comment by Sayanta66** [comment]
@falondarville review it :)

**Comment by Bradamant3** [comment]
@Sayanta66 please don't `@` any specific maintainer -- we share the work of responding to contributions, and we get to them as time permits.

For this PR in particular, please update according to the the [Kong style guide](https://docs.konghq.com/contributing/style-guide/). When you do, make sure to set a conversational tone and use active voice wherever possible. Unfortunately our time is limited and we can't provide details about the changes you need to make. Thanks!

**Comment by Sayanta66** [comment]
Okay noted

**Comment by Bradamant3** [comment]
@Sayanta66 I'm sorry, you've clearly put some effort into this PR, but you seem to have trouble figuring out appropriate use of passive/active voice, and you also seem to confuse "conversational" (in the style guide) with "colloquial". "Gets ..." is harder to parse that the original you suggested changes to, for example. I need to close unmerged -- you've submitted quite a few PRs with similar issues. I'll hold off on closing the others in case you can figure out the problems better there. Thanks for understanding!

**Comment by Sayanta66** [comment]
@Bradamant3 can you tell me in details what is the thing that needs to be changed? Because I solved all the article and punctuation errors

**Comment by Sayanta66** [comment]
I will surely review the others in a bit

**Pull request closed without merging**
