### PR TITLE
Add Heroku Kong deployment listing to Hub

### PR DESCRIPTION
**Pull request by mars**

### CODE REVIEW

**Comment by coopr** [comment]
Awaiting additional review from Kong Inc. colleague...

**Comment by thefosk** [comment]
Looks good to me

**Comment by coopr** [comment]
Merged and deployed - thanks for your contribution @mars - you have earned the special distinction of being the first ever post-launch contribution to the Kong Hub https://docs.konghq.com/hub/ 🥇

**Comment by mars** [comment]
Woo hoo! 🎉  Thanks to you folks for your continuous drive improving Kong 🙌

**Pull request merged**
