### PR TITLE
Add Vitals Estimate page

### PR DESCRIPTION
**Pull request by hhoover**
### Summary
This page provides information about how Kong Vitals stores data
to give customers estimates on PostgreSQL sizing needs.

### Reason
Help folks get a better idea of how large PostgreSQL needs to be

### CODE REVIEW

**Comment by Bradamant3** [comment]
@sichvoge wdyt? Seems like an excellent page to add, yes? (I urged Hart to add it, so blame me if you don't like the idea :D )

**Comment by falondarville** [comment]
Hi @hhoover, this is great! I checked the fork and it's 799 commits behind main. Are you okay with me moving this to a branch and giving you attribution?

**Comment by hhoover** [comment]
Go for it!

**Comment by falondarville** [comment]
Closing as content has been moved to (3544)[https://github.com/Kong/docs.konghq.com/pull/3544].

**Pull request closed without merging**
