### PR TITLE
Plugin Tag Executor. Initial plugin docs.

### PR DESCRIPTION
**Pull request by Apxdono**
### Summary

This PR adds hub documentation for new 3rd party plugin [tag-executor](https://github.com/Apxdono/kong-plugin-tag-executor)
### Testing

Ran locally as per [instructions](https://docs.konghq.com/contributing/plugin-docs/#writing-plugin-documentation) on adding new plugin documentation.

review:general

### CODE REVIEW

**Comment by mheap** [comment]
@kongguogang Is this something you could look at?

**Comment by Apxdono** [comment]
@mheap This indeed took some time? could it be that nobody reviews this PR since the build isn't green? (IDK how to fix it, I see that multiple PRs failed with same issue in the past).

**Comment by mheap** [comment]
@Apxdono The build failure is unfortunate (but is ok!). We're struggling to get bandwidth from the person that owns plugins to review. Leave it with us

**Comment by cloudjumpercat** [comment]
@kongguogang Could you look over this new plugin documentation when you have the chance? Thanks!

**Comment by cloudjumpercat** [comment]
Hi @Apxdono ! Thanks for submitting this. I talked with our product manager for the plugin hub, and he said that they've reviewed the new plugin and decided not to proceed with it, so I'll close this PR for now. If you have any questions, you can reach out to gang.guo@konghq.com. Thanks again!

**Comment by Apxdono** [comment]
@cloudjumpercat Good day, just got around to this PR and tried to reach Gang Guo, but received the following `Hi - you've reached an invalid email address.` from Kong mail server. Can you point me to the new PM email I can talk about the closing of PR and plugin in general?

**Comment by cloudjumpercat** [comment]
Hi @Apxdono ! Thank you for your support and contributions to the Kong Plugin Hub. At this time, Kong will only be maintaining plugin listings for verified partners. This means we will no longer maintain entries of custom plugins from community or individual contributors.
If you would like to have your plugin featured on the Kong Plugin Hub in the future, we encourage you to [become a Kong Partner](https://konghq.com/partners).

**Pull request closed without merging**
