### PR TITLE
Microsoft Azure Deployments - Support 0.13, 0.15, 1.0 & 1.1

### PR DESCRIPTION
**Pull request by tomkerkhove**
### Summary

Support 0.13, 0.15, 1.0 & 1.1 for `Microsoft Azure Container Instances` & ` 
Microsoft Azure` Deployment Plugins.

### Full changelog

* Added support for Kong 0.13, 0.15, 1.0 & 1.1

### Issues resolved

N/A

### Checklist:

- [X] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation  N/A
- [X] [Adheres to Kong style guide](https://github.com/Kong/docs.konghq.com/blob/master/STYLEGUIDE.md)
- [X] Spellchecked my updates
- [x] Tagged "Team Docs" as reviewers
- [X] Ready to be merged 

Relates to https://github.com/tomkerkhove/kong-deployment-on-azure/issues/5

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Will fix the commit message.

**Comment by h3xar0n** [comment]
Hi @tomkerkhove , could we also list that it's compatible with Enterprise 0.35, which inherits from CE 1.0.3? 

@shashiranjan84 , based on our discussion.

**Comment by tomkerkhove** [comment]
@h3xar0n I don't have access to an enterprise version of Kong but if you confirm that it works I'm happy to add it!

**Comment by h3xar0n** [comment]
@tomkerkhove I will check, thank you! And just to be sure, 0.13 is not supported?

**Comment by tomkerkhove** [comment]
I've tested this with 0.14 but not with 0.13, I'll see if I have some time to try it out but I'm pretty sure it's supported as well.

**Comment by h3xar0n** [comment]
Yes please let us know!

**Comment by tomkerkhove** [comment]
Tracking this in https://github.com/tomkerkhove/kong-deployment-on-azure/issues/6 to avoid having to keep this open due to this.

**Comment by tomkerkhove** [comment]
@h3xar0n 0.13 works

**Comment by h3xar0n** [comment]
Fantastic, thank you for testing and for the updates, @tomkerkhove . 

We may test internally down the road to check for Enterprise compatibility, and if it's confirmed, I can create a new issue for you. For now, I'd like to approve and merge. Sound good?

**Comment by tomkerkhove** [comment]
That sounds perfect to me @h3xar0n! Thanks for helping!

**Pull request merged**
