### PR TITLE
docs(mesh): adjust external ca verification docs since 2.4.0

### PR DESCRIPTION
**Pull request by slonka**
### Description

The docs wrong since 2.4.0 - we changed the implementation.
 

### Testing instructions

Preview link: 

### Checklist 

- [X] Review label added 
- [X] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by fabianrbz — APPROVED** [review]
LGTM

**Comment by slonka** [comment]
tests are failing :(

**Comment by fabianrbz** [comment]
I'll look into this, they are failing because of a missing env variable `VITE_PORTAL_API_URL` I guess it's not set on your fork

**Comment by slonka** [comment]
> I'll look into this, they are failing because of a missing env variable VITE_PORTAL_API_URL I guess it's not set on your fork

so can I just merge it?

**Pull request merged**
