### PR TITLE
WIP - HELP - terraform provider kong documentation

### LINKED ISSUE #43: Events for newsletter subscription and enterprise demo request
1. For the enterprise form and the newsletter updates, when you call identify, please also add "created_at" = datetime (unix time)

2. For the enterprise form, on submit, please also call analytics.track event for “request_enterprise_demo" with the properties.
Example:
```
analytics.track('request_enterprise_demo',{
    company: 'Mashape',
    deployment: 'on-prem',
    email: 'christina+test3@mashape.com',
    name: 'christina test',
    phone: '4321',
    request_date: date/time of submission
})
```
3. For the newsletter updates, same thing, on submit, please call analytics.track event for “request_newsletter_updates” with the properties. 

Alternatively, you can use the trackform function instead of track, whichever one is easier for you - https://segment.com/docs/libraries/analytics.js/#track-form

Basically, if the same user (same email) submits the form twice, it should call the analytics.track event twice with two different submit date/time.

### PR DESCRIPTION
**Pull request by kevholditch**
# Help
I must be missing something as my new tile is not appearing on the hub page.  I'm not sure why, could someone please help

**NOTE**: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md

### Summary

Adding deployment documentation for terraform provider kong

### Full changelog

* Added terraform provider kong documentation as per [request](https://github.com/kevholditch/terraform-provider-kong/issues/43) 

### Issues resolved

Fix https://github.com/kevholditch/terraform-provider-kong/issues/43

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation 
- [x] Spellchecked my updates
- [ ] Ready to be merged

### CODE REVIEW

**Comment by h3xar0n** [comment]
Hi @kevholditch , I see it appearing locally, albeit without an image:

screen shot 2019-02-22 at 1 28 30 pm

I'm able to get there by visiting `localhost:3000/hub`. The issue may be that the Hub link in navigation is an absolute path that goes to the live doc site.

**Comment by levfishbluefish** [comment]
Hi @kevholditch - I've confirmed that it is working locally, you might be clicking the "hub" link in the header which will take you to the **live** hub page on docs.konghq.com

When running it locally you can see it at 
http://localhost:3000/hub/ 
and
http://localhost:3000/hub/kevholditch/terraform-provider-kong/

**Comment by subnetmarco** [comment]
Hi Guys, I think this should show up in the [Installation Page](https://konghq.com/install/) rather than in the Kong Hub, under a Terraform icon.

**Comment by kevholditch** [comment]
@levfishbluefish added default image or do we want to move this now?  As per the comment from @subnetmarco?  Think you could argue it either way between deployment and installation.  Personally I think its more deployment as the provider doesn't help you install or run kong it simply configures an installation of kong that is already running. 

The reason I put it in hub is that's where @coopr [asked me to put it](https://github.com/kevholditch/terraform-provider-kong/issues/43) Happy to put it wherever is deemed best.

**Comment by levfishbluefish** [comment]
@kevholditch lets go ahead and move this to the installation page

**Comment by hbagdi** [comment]
> @subnetmarco? Think you could argue it either way between deployment and installation. Personally I think its more deployment as the provider doesn't help you install or run kong it simply configures an installation of kong that is already running.


I agree.
The provider helps us configure Kong and not deploy or install Kong using Terraform.
Most users will be confused because Terraform is widely used for deployment and installation.

Keep in mind that we have a Terraform module which can be used to deploy Kong as well: https://docs.konghq.com/hub/zillowgroup/kong-terraform/

I would suggest that we introduce a new category of Configuration, under which projects like these and other tools by the community, like Konga can be put.

Also, @kevholditch Thank you for building the Terraform provider for Kong! 🙇

**Comment by levfishbluefish** [comment]
> > @subnetmarco? Think you could argue it either way between deployment and installation. Personally I think its more deployment as the provider doesn't help you install or run kong it simply configures an installation of kong that is already running.
> 
> I agree.
> The provider helps us configure Kong and not deploy or install Kong using Terraform.
> Most users will be confused because Terraform is widely used for deployment and installation.
> 
> Keep in mind that we have a Terraform module which can be used to deploy Kong as well: https://docs.konghq.com/hub/zillowgroup/kong-terraform/
> 
> I would suggest that we introduce a new category of Configuration, under which projects like these and other tools by the community, like Konga can be put.
> 
> Also, @kevholditch Thank you for building the Terraform provider for Kong! 🙇

@subnetmarco I'll give you the final say

**Comment by subnetmarco** [comment]
We should have a "Terraform" icon in the installation page, and within that page we can have two sections: "Installing with Terraform" and "Configuring with Terraform". It's more likely for a user trying to use Kong via Terraform to do so via the Installation page and Terraform link, rather than scrolling the Hub. In fact, I would like to move all the "Deployments" in the Hub to the Installation page in a specific "Community Contributed" section.

In the meanwhile, we can make that clear by adding a note to the Terraform page, but still have it visible in the installation page.

**Comment by Bradamant3** [comment]
and another unsigned CLA.

**Pull request closed without merging**
