### PR TITLE
updates required fields for request-validator plugin

### PR DESCRIPTION
**Pull request by dimitropoulos**
it appears that these are not actually required because they have defaults

### Review

@reviewer

### CODE REVIEW

**Comment by tlblessing** [comment]
@dimitropoulos regardless of defaults, the schema indicates allowed_content_types is a required field 
image
cc: @murillopaula .

**Comment by dimitropoulos** [comment]
I'm sorry, I don't understand.  A default refers to the behavior when it's not set, but required means that it cannot _not_ be set.  This seems to be a contradiction to me.  Am I missing something?

In other words, if it's required then it does't make sense to have a default because that default value would never be used (because the user must always provide their own value because it's required).

**Comment by tlblessing** [comment]
> I'm sorry, I don't understand. A default refers to the behavior when it's not set, but required means that it cannot _not_ be set. This seems to be a contradiction to me. Am I missing something?
> 
> In other words, if it's required then it does't make sense to have a default because that default value would never be used (because the user must always provide their own value because it's required).

Perhaps a bug ticket should be logged to update the schema.

**Comment by lena-larionova** [comment]
Closing this and taking to a separate project/conversation, as there is a bigger problem here.

**Pull request closed without merging**
