### PR TITLE
docs(*) add autodocs files

### PR DESCRIPTION
**Pull request by gszr**
### Review

@Kong/team-docs 

### Summary

Add autodocs files for:
- configuration reference
- admin api
- db-less
- pdk

### CODE REVIEW

**Comment by lena-larionova** [comment]
🙌 
What went wrong with the scripts originally (other than the wrong branch being targeted)? Is there something we can add to the readme to clarify the instructions?

**Comment by gszr** [comment]
>  What went wrong with the scripts originally (other than the wrong branch being targeted)? Is there something we can add to the readme to clarify the instructions?

The release branch was missing some autodocs data; also, the PDK guide section was renamed on the docs repo, so the script did not find the line it needs to fill in the PDK docs (fix is here https://github.com/Kong/kong/pull/6991).

**Comment by lena-larionova** [comment]
> The release branch was missing some autodocs data; also, the PDK guide section was renamed on the docs repo, so the script did not find the line it needs to fill in the PDK docs (fix is here [Kong/kong#6991](https://github.com/Kong/kong/pull/6991)).

When did that happen? We currently have both a Plugin Development Kit and a Plugin Development Guide section, and both have been around for quite some time - I think kit is the one you still want, and not overwrite the guide section.

https://docs.konghq.com/gateway-oss/2.3.x/pdk/ - aka "kit", this one has always been generated
https://docs.konghq.com/gateway-oss/2.3.x/plugin-development/ - aka "guide", this one gets manually updated

**Comment by lena-larionova** [comment]
Rebasing this PR to pick up a bunch of link fixes and force a deploy preview.

**Comment by lena-larionova** [comment]
@gszr for when you're back - this looks good except the PDK bit. With the deploy preview working, I was able to check the output, and my instinct was right... looks like the guide got overwritten: 
https://deploy-preview-2736--kongdocs.netlify.app/gateway-oss/2.4.x/pdk/
Screen Shot 2021-04-02 at 9 58 08 AM

**Comment by gszr** [comment]
@lena-larionova I've pushed it again, can you re-review?

**Comment by gszr** [comment]
@lena-larionova any ideas why all those links are broken?

**Comment by lena-larionova** [comment]
@gszr looks like every one of those broken links is actually the same thing: /gateway-oss/2.4.x/pdk/kong.cluster

 Is kong.cluster a new module? I don't see it anywhere before 2.4.x. If that's the case, then it looks like a table of contents entry is being generated for kong.cluster, but a markdown page isn't.

**Comment by gszr** [comment]
> @gszr looks like every one of those broken links is actually the same thing: /gateway-oss/2.4.x/pdk/kong.cluster
> 
> Is kong.cluster a new module? I don't see it anywhere before 2.4.x. If that's the case, then it looks like a table of contents entry is being generated for kong.cluster, but a markdown page isn't.

Good catch. The autodoc script wasn't copying all PDK markdown files. Added the fix here: https://github.com/Kong/kong/pull/6996

**Pull request merged**
