### PR TITLE
Grammar Correction

### PR DESCRIPTION
**Pull request by JesseSumrak**
**NOTE**: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md

### Summary

SUMMARY_GOES_HERE

### Full changelog

* [Edited docs to ...]
* [Added cool new feature ...]
* ...

### Issues resolved

Fix #XXX

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation 
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by coopr** [comment]
Please combine all your contributions into one PR, please.

**Comment by coopr** [comment]
Nice fix, but please combine into your other PR #979

**Comment by shinypenny31** [comment]
Hey @coopr! Don't want to cause more trouble than I'm worth :P but this is my first time contributing—how do I go about combining to my other PR?

**Comment by coopr** [comment]
To add things to a given PR, you'll add commits to the branch that you are PR'ing - hope that makes sense :)

How you actually do that varies a little depending on if you are using the GitHub web interface, using GitHub desktop app (I'm a big fan of it, BTW), or using Git on the command line.

**Pull request merged**
