### PR TITLE
fix: Using Gateway Discovery

### PR DESCRIPTION
**Pull request by Rajakavitha1**
### Description

Tested, validated, and rewrote the guide.

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by mheap** [comment]
This guide is out of date. We have two options:

1. Use the `kong/ingress` chart which uses Gateway Discovery by default. Then the guide is about how to enable mTLS
2. Use `kong/kong` and treat it as a migration guide for those that are currently running with `kong/kong` and a sidecar model

@mflendrich Any preferences?

**Comment by Rajakavitha1** [comment]
> This guide is out of date. We have two options:
> 
> 1. Use the `kong/ingress` chart which uses Gateway Discovery by default. Then the guide is about how to enable mTLS
> 2. Use `kong/kong` and treat it as a migration guide for those that are currently running with `kong/kong` and a sidecar model
> 
> @mflendrich Any preferences?

@mheap please confirm if the install instructions on https://docs.konghq.com/kubernetes-ingress-controller/latest/deployment/minikube/ for helm needs to be updated as well because right now we are using ```helm install kongdocs kong/kong```

**Comment by mheap** [comment]
Yes, we should use `kong/ingress` in all KIC documentation. `kong/kong` is for the Gateway only deployments

**Comment by mheap** [comment]
Let's make this a guide on how to migrate from non-Gateway Discovery to Gateway Discovery deployments.

I'll take the action item to write then Rajie can review.

**Comment by Rajakavitha1** [comment]
> Let's make this a guide on how to migrate from non-Gateway Discovery to Gateway Discovery deployments.
> 
> I'll take the action item to write then Rajie can review.

Should I mark this PR as closed with a note that a new Migration PR is being created.

**Pull request closed without merging**
