### PR TITLE
WIP [DOCU-2126] rm duplicate ref

### PR DESCRIPTION
**Pull request by falondarville**
### Summary

Remove duplicated reference from Dev Portal SMTP Configuration and Managing Developers on 2.8.x. These pages now direct users to the comprehensive reference. We don't have to maintain multiple identical definitions now. 

### Reason

Addresses https://konghq.atlassian.net/browse/DOCU-2126

### Testing

Note that I am opening a PR on the kong-ee repo to update all definitions in the comprehensive reference. 

https://deploy-preview-3751--kongdocs.netlify.app/gateway/2.8.x/developer-portal/configuration/smtp/
https://deploy-preview-3751--kongdocs.netlify.app/gateway/2.8.x/developer-portal/administration/managing-developers/

Edit: We are going to wait for the merge to go through over on the kong-ee side to ensure that we can generate the doc and add the updated generated file to this PR. This way, we're not missing the more comprehensive config definitions.

### CODE REVIEW

**Comment by lena-larionova** [comment]
Parallel PR: https://github.com/Kong/kong-ee/pull/3036
PR was closed automatically when Falon left Kong, I'll have to open a new one with the same changes.

**Comment by mheap** [comment]
Upstream PR reopened at https://github.com/Kong/kong-ee/pull/3180

**Comment by mheap** [comment]
@lena-larionova Upstream merge went through. Should we run autodoc to regenerate or merge this PR?

**Comment by lena-larionova** [comment]
> Should we run autodoc to regenerate or merge this PR?

Let's merge for now. Autodoc should cover anything going forward.

**Review by lena-larionova — APPROVED** [review]

**Comment by lena-larionova** [comment]
Can merge together with https://github.com/Kong/docs.konghq.com/pull/3951

**Pull request merged**
