### PR TITLE
Feat/auto deploy

### PR DESCRIPTION
**Pull request by levfishbluefish**
### Summary

Test for auto-deploying to gh-pages on push to master branch, following https://github.com/BryanSchuetz/jekyll-deploy-gh-pages 

### Checklist:

- [X] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [X] Documentation 
- [X] [Adheres to Kong style guide](https://github.com/Kong/docs.konghq.com/blob/master/STYLEGUIDE.md)
- [X] Spellchecked my updates
- [X] Ready to be merged

### CODE REVIEW

**Comment by hutchic** [comment]
This looks like it's running the github action on all branches. Is it possible to restrict the github action to the master branch only?

**Comment by levfishbluefish** [comment]
@hutchic I _think_ thats what the `args = branch master` is doing

**Comment by hutchic** [comment]
@levfishbluefish that's setting what branch it deploys but the `Build and Deploy Jekyll` job that ran on this PR (I think).

Capture

**Comment by levfishbluefish** [comment]
@hutchic Ok I think I figured it out - I added a `action filter` with the argument 'branch master' so it shouldn't trigger the build step unless it is on that branch. You might see the Filter run on a PR to determine if it is on the master branch or not

**Pull request merged**
