### PR TITLE
Revise KIC rate-limiting guide to use Secrets Management

### PR DESCRIPTION
**Pull request by rainest**
### Description

For https://github.com/Kong/kubernetes-ingress-controller/issues/4558

Refresh the KIC rate-limiting with Redis guide and add a Secrets Management section to it. Link the same guide from the sidebar as a Secrets Management guide. Several of the commits are basic formatting changes; most of the interesting content is in the later commits.

Most of an end-to-end Secrets Management guide is creating and testing a plugin, with only one minor step to add a vault  key and set the plugin to use it. Supported config fields for Secrets Management are also restricted, so we're mostly limited to plugins that can use authentication. Authentication unfortunately happens under the hood and isn't readily visible, but :shrug: 

Redis doesn't provide a convenient mechanism for setting a password using the base image currently used in the guide (it apparently requires awkwardly shoving a CLI argument into the container command), so this guide now uses the Bitnami Helm chart. I would prefer to avoid 3rd-party install methods, but the 1st-party Redis operator is apparently only for paid offerings (docs aren't entirely clear, but they label it "enterprise" and don't say that it can be used with free offerings). I don't think we want to keep the old one, as it doesn't offer anything other than not using Helm, but the initial content commit keeps it in tabs if we do want to.

### Testing instructions

Netlify link: https://deploy-preview-6069--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/redis-rate-limiting/

The Enterprise badge is causing formatting weirdness around https://deploy-preview-6069--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/redis-rate-limiting/#optional-use-secrets-management for reasons I do not understand.

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by rainest** [comment]
Something screwy is going on with the `{:.badge .enterprise}` badge:

https://deploy-preview-6069--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/redis-rate-limiting/#optional-use-secrets-management

**Comment by Rajakavitha1** [comment]
Hi @rainest Thank you for the PR. I just validated the steps that you have in the deploy review. Every thing works as documented. However, I dont seem to get any output when I get to the "Test It" section. Here's the terminal output for your reference. Please let me know if I am missing something. 
[nosecretmanagementredis.txt](https://github.com/Kong/docs.konghq.com/files/12608679/nosecretmanagementredis.txt)

**Comment by Rajakavitha1** [comment]
> Something screwy is going on with the `{:.badge .enterprise}` badge:
> 
> https://deploy-preview-6069--kongdocs.netlify.app/kubernetes-ingress-controller/latest/guides/redis-rate-limiting/#optional-use-secrets-management

Fixed this in the latest commit.

**Comment by rainest** [comment]
The Redis hostname was from an outdated name I'd used earlier in testing and the plugin was failing open.

Fixed that and tidied up some naming/spacing elsewhere.

**Review by Rajakavitha1 — APPROVED** [review]
LGTM

**Comment by Rajakavitha1** [comment]
tested and validated the guide. It works as documented. 
[ratelimitingworks.txt](https://github.com/Kong/docs.konghq.com/files/12616405/ratelimitingworks.txt)

**Review by mheap — APPROVED** [review]

**Pull request merged**
