### PR TITLE
change docs keys link keys-entity to keys-object

### PR DESCRIPTION
**Pull request by raoxiaoyan**
### Summary

INTF-2990 Need to update docs keys link keys-object instead of keys-entity
### Reason

I need to keep the link of `Keys` to the same specification as the links of other entities. Because the docs of the new vaults in KM 3.2 cannot link to the corresponding page correctly

### CODE REVIEW

**Comment by Guaris** [comment]
This will break the link unless the section is renamed both in the doc and in the api docs. Here is an explanation in your other PR
https://github.com/Kong/docs.konghq.com/pull/4910#issuecomment-1349068600

**Comment by cloudjumpercat** [comment]
@raoxiaoyan Hi! If you could check out the comment Angel made [here](https://github.com/Kong/docs.konghq.com/pull/4909#issuecomment-1349202443) and make the suggested changes to the section name, that would be great! Thanks!

**Comment by cloudjumpercat** [comment]
@raoxiaoyan Hi! Could you rename the section in the API doc as well so that the link to the vaults object section resolves? If you wanted to rename vaults-entity to vaults object you would have to rename it in the admin-api.lua https://github.com/Kong/kong/blob/master/autodoc/admin-api/data/admin-api.lua#L2203
and line 449 of /admin-api/index.md https://github.com/Kong/docs.konghq.com/edit/fix/vaults-link/src/gateway/admin-api/index.md

**Comment by Guaris** [comment]
I'm trying to understand what you are trying to do. I read the brief in the linked [ticket](https://konghq.atlassian.net/browse/KAG-394)  but the documentation requirement is different than the one you are writing here. 

I think you are trying to change the anchor link for the key entity object in the admin API docs. I wrote instructions on how to do that in https://github.com/Kong/docs.konghq.com/pull/4909 


I'm closing this ticket, please feel free to open it if you want to discuss this further. Or message me in Slack @angel and we can go over this together.

**Pull request closed without merging**
