### PR TITLE
docs(hub) optum logo update

### PR DESCRIPTION
**Pull request by coopr**
### Summary

Update logo for Kong Hub listings published by Optum

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [ ] Documentation N/A
- [ ] Spellchecked my updates N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by rsbrisci** [comment]
Thanks Cooper :+1:

**Comment by rsbrisci** [comment]
Actually cooper - Could we delay this merge for a bit? I need to have the branding team check my handiwork before we can go fully public.

**Comment by coopr** [comment]
I've labeled this PR to hold merge @rsbrisci - I'll remove those labels when you say so. No rush, we can tune this up anytime.

**Comment by jeremyjpj0916** [comment]
We have gained approval from our branding team.
Thanks,
Jeremy

**Comment by jeremyjpj0916** [comment]
@coopr Any ideas when this will go live to see the Logo in action?

**Comment by coopr** [comment]
@jeremyjpj0916 this should get deployed later today.

**Pull request merged**
