### PR TITLE
docs(vitals): remove content for vitals reports

### PR DESCRIPTION
**Pull request by sumimakito**
### Summary

This pull request removes content for Vitals Reports as it was actually removed since the previous version (3.0).

Please feel free to point out if I missed out anything.

### CODE REVIEW

**Comment by cloudjumpercat** [comment]
@sumimakito Thanks for submitting this PR! I think the tests are failing because the Analytics report file was deleted. Since this content is single sourced, deleting the file from the nav like you did should be enough. Could you restore the Analytics report file?

**Comment by sumimakito** [comment]
@cloudjumpercat Thanks for the advice. I have restored the deleted file.

**Review by cloudjumpercat — APPROVED** [review]
LGTM!

**Comment by acgoldsmith** [comment]
Relates to https://konghq.atlassian.net/browse/INTF-2983

**Pull request merged**
