### PR TITLE
Dbg add traceable plugin

### PR DESCRIPTION
**Pull request by dbgordon**
### Summary

Add Traceable integration to Kong Hub.

### Reason

Per discussion with Gang Guo.

### Testing

Local doc build.

### CODE REVIEW

**Comment by cloudjumpercat** [comment]
@kongguogang When you have a chance, could you review this plugin doc? Thanks!

**Comment by kongguogang** [comment]
we will park it during v3.2 release, will resume it after v3.2 released

**Comment by dbgordon** [comment]
Thanks @kongguogang and @cloudjumpercat. Rough timeframe on when we can pick this back up? Days, weeks, months, quarters? Thanks.

**Comment by dbgordon** [comment]
@cloudjumpercat Hi I could use some assistance here. Apparently, the build failed thinking that I have an incorrectly spelled word, which I don't.

`[vale] reported by reviewdog 🐶
[kongplugins.Pluginspelling] Did you really mean 'exfiltration'?`

How do I tell it that "exfiltration" is exactly the word I want and that it should stop flagging it?

Thanks for your help.

**Comment by cloudjumpercat** [comment]
@dbgordon Hi! If you add it to [this file](https://github.com/Kong/docs.konghq.com/blob/main/.github/styles/kongplugins/dictionary.txt) (this is the dictionary that Vale uses when looking for spelling errors, words in here will be treated as correct spellings), that should fix the problem!

**Comment by dbgordon** [comment]
Hi reviewers. Is there anything else that I need to do to get this change approved and published (to the Kong Hub)? Thanks!

**Comment by acgoldsmith** [comment]
Hi @dbgordon , we'll work w/ responsible parties internally to set some timelines for this release. Thank you.

**Comment by dbgordon** [comment]
Thanks, @acgoldsmith. Any ETA on this? Can we get it done by end of this month? Thanks.

**Comment by dbgordon** [comment]
@acgoldsmith @kongguogang

Are there any corrections that I need to make with my Kong Hub submission, or is there something else I need to fix, to get this change merged? Please let me know how I can get this update accepted.

  Thanks,
  Dan Gordon
  Traceable

**Comment by acgoldsmith** [comment]
@dbgordon, apologies for the delayed response - Gang is not involved in this process anymore, so I'm looking for another internal point of contact who can assess this addition from strategic perspective before we move ahead with publishing.

**Pull request closed without merging**
