### PR TITLE
docs(km) note Kong Manager perf issue in traditional mode

### PR DESCRIPTION
**Pull request by mayocream**
### Summary

Add a note for the Kong Manager perf issue in traditional mode.

### Reason

We are telling the clients that using Kong Manager in traditional mode may have an impact on the overall performance of the Kong.

INTF-2900

### CODE REVIEW

**Comment by mheap** [comment]
@mayocream Why is this only an issue in traditional mode as opposed to Hybrid mode?

**Comment by mayocream** [comment]
> @mayocream Why is this only an issue in traditional mode as opposed to Hybrid mode?

I might not express it clearly; the Kong Manager (Lua code in EE) consumes CPU, I/O resources to calculate and handle frontend user operations, if the client runs in the traditional mode (not Hybrid), this would increase the Kong Proxy's P99 latency.

But in the Hybrid mode, the Kong Manager only runs in the CP node, not impact on the DP performance.

**Comment by mayocream** [comment]
> @Guaris I wouldn't look for this information in the Hybrid mode docs. It'd work well in a Kong Manger section if we have one

We had a [Kong Manager section (<= 2.5.x)](https://github.com/Kong/docs.konghq.com/tree/main/app/enterprise/2.5.x/kong-manager), but got removed in the latest docs :( 

@Kong/team-km will probably start a conversation internally about this.

**Comment by Guaris** [comment]
Understood, then this is a good place for now.

**Review by Guaris — APPROVED** [review]

**Comment by mheap** [comment]
@Guaris Could we issue a followup PR explaining why proxy performance may be impacted in traditional mode and why it's not an issue in hybrid mode?

**Pull request merged**
