### PR TITLE
Add "Back to TOC" link

### PR DESCRIPTION
**Pull request by vinayak42**
Signed-off-by: Vinayak vinayak17122@iiitd.ac.in

**NOTE**: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md

### Summary

Add missing "Back to TOC" link in configurations.md

### Issues resolved

Fix #XXX

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation 
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by coopr** [comment]
There are many, many places in our docs that'd benefit from these "Back to ToC" links - for example https://docs.konghq.com/0.14.x/health-checks-circuit-breakers/ and https://docs.konghq.com/0.14.x/auth/ are both rather long pages that would be helped by the addition of such links.

Ideally, the solution to this is an automated one - longer pages could get "Back to ToC" links automatically inserted above headings (skipping the first one or two) at build time.

If instead you'd like to add them manually, you are welcome to do so - but to make this a valid PR, please add MANY more of them :)

**Comment by vinayak42** [comment]
@coopr thanks for the heads up. I'll be adding more commits to this PR.

**Comment by vinayak42** [comment]
@coopr I have made another PR as I thought the description should have been elaborated. Kindly refer to #997 . Thanks!

**Comment by coopr** [comment]
Closing in favor of #997

**Pull request closed without merging**
