### PR TITLE
Modify the Error 404 Page

### PR DESCRIPTION
**Pull request by Rutam21**
### Summary
This PR modifies the existing Error 404 Page and tries to bring in some animation that enhances the user experience.

### Reason
Resolves this issue: https://github.com/Kong/docs.konghq.com/issues/3154

### Testing
This PR is complete. The preview build looks good.

### Preview
https://deploy-preview-3248--kongdocs.netlify.app/404

### CODE REVIEW

**Comment by Rutam21** [comment]
I have tried to bring in some creativity with the animations. However, `fa-monkey` was supposed to be there instead of the `fa-spider` but that is available to Pro users only. We should probably suggest Font Awesome make a  `fa-kong` icon instead 😀. Let me know if it looks good to you.

@lena-larionova  @falondarville

**Comment by falondarville** [comment]
Thank you so much, @Rutam21! This is very creative! I verified the changes with our company branding and have some feedback:

- Reduce spacing between elements so that the user can clearly see the information "before the fold"
- Remove the moving spider element (it's super cute, but it doesn't meet our company branding standard, unfortunately!)
- Change the H4 to `li` as the H4 currently skips header levels (from H2 to H4), and `li` will make it easier for screenreader users to understand the content (see some of our [Accessibility Efforts](https://docs.konghq.com/contributing/community-expectations/#accessibility))

**Comment by Rutam21** [comment]
@falondarville I made some changes based on your feedback. Please let me know what you think about it now.

**Review by falondarville — COMMENTED** [review]
One more (text change that was there before) and it should be ready! Thank you for incorporating the feedback! 🎉

Realized that we linked to the homepage twice!

**Review by falondarville — APPROVED** [review]
Looks good to me! Thank you so much!

**Comment by falondarville** [comment]
Hi @Rutam21, if you haven't done so yet - don't forget to enter for a T-shirt and possible prize on the Kong Summit page: https://konghq.com/summit-hackathon/.

**Comment by Techie-Manju** [comment]
@falondarville Thanks for the reminder. I almost forgot about it 😅. Bdw, do I need to add all my PR/merged PR links or just one?

**Comment by Techie-Manju** [comment]
@falondarville Thanks for the reminder. I almost forgot about it 😅. Bdw, do I need to add all my PR/merged PR links or just one?

**Comment by Rutam21** [comment]
Lol, @Techie-Manju 😂 That reminder was supposed to be for me I guess. I am not sharing my T-shirt. So, you gotta raise a PR and earn it for yourself 😉

**Comment by falondarville** [comment]
@Techie-Manju go ahead and submit each PR!

**Comment by Rutam21** [comment]
@falondarville I thought this was good enough to win the Docs category. It was such an Oops moment😣. I would love to have feedback on what was missing in my contributions. Thanks. 
You can mail me at **rutamprita@gmail.com**

**Comment by falondarville** [comment]
@Rutam21 we received your email and responded!

Thank you again for your submission. 

Unfortunately, we could only pick one winner for this Hackathon and with many excellent entries, our team had difficult decisions to make. Rest assured that the Kong docs team thoroughly reviewed all entries and as is the nature of a competition, they simply decided on another submission as the winner. 

Thanks for your entry and we hope to bring more events like this to you in the future, especially seeing the popularity and enthusiasm in the docs category.

**Pull request merged**
