### PR TITLE
docs(ee-k8s) Move k8s topics into deployment section and update

### PR DESCRIPTION
**Pull request by lena-larionova**
### Changes
* Rephrase inaccurate descriptions for Kubernetes installation topics.
_Note: Currently, our two installation topics are basically split up into DB-backed and DB-less; I updated the descriptions to reflect this. This is probably not the way to go to organize them for the future, however. I'd like to try and combine the two topics next week, but that might take some work._ 
* Move Kubernetes deployment and overview content into the deployment section of the docs - the deployment options topic has been notoriously hard to find.
* Update links and redirects to cover the move.
* Delete old, empty k8s changelog topic that's only there as a redirect.
* Update diagrams to match the style used in other deployment topics (eg https://docs.konghq.com/enterprise/2.1.x/deployment/classic-deployment/).

### Comments for reviewers
I have a concern about the [Kong for Kubernetes Enterprise overview topic](https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/kong-for-kubernetes-enterprise/). Currently, the majority of the description focuses on the db-less KIC deployment, and there's very little about the full Enterprise install. @marcoam @felderi do we have a blurb somewhere about the benefits of the full install that I can add? 

### Previews
[Kong for Kubernetes Enterprise overview](https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/kong-for-kubernetes-enterprise/) - needs a better title to encompass both installation types, or, we need to fix our naming.
[Deployment Options](https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/kubernetes-deployment-options/)
[Install Kong for Kubernetes Enterprise](https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/kong-for-kubernetes/)
[Install Kong Enterprise on Kubernetes](https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/install-on-kubernetes/)

### CODE REVIEW

**Comment by marcoam** [comment]
Hey @lena-larionova - Very great job! Definitely getting a lot better. But I do have some comments: 

1) Taking a look at this page: https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/kong-for-kubernetes/, there's a "loopback" URL on the text "Installing Kong Enterprise on Kubernetes". It should be pointing to: https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/install-on-kubernetes/
2) Perhaps, to avoid confusion it may make sense to change the URL: 
https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/**install**-on-kubernetes/
to something like: 
https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/**kong**-on-kubernetes/
Just a thought...
3) Regarding the question you asked. I attempted to describe both of the options, and which one to pick, depending on the use case:

```Kong provides two packages that you can deploy, depending on your use case. Kong *for* Kubernetes Enterprise is not the complete Kong Enterprise platform, but rather, it's a Kubernetes Ingress Controller. The Ingress Controller runs without the need of a database and supports the vast majority of Kong's plugins, including the Enterprise ones. However, it is important to highlight that features such as Kong Manager, Kong Analytics (Vitals), Kong Developer Portal, RBAC, workspaces and many other features aren't able to be ran. 
In contrast, Kong Enterprise **on** Kubernetes will run the whole full-fledged platform. This platform includes Kong Manager, Kong Analytics (Vitals), Kong's Developer Portal, RBAC, workspaces, all plugins and other features. As there are functionalities in this platform that require a stateful environment, a database is required to run this package. 

The Kong Enterprise **on** Kubernetes is the ideal install for those organizations that are looking to leverage Kong's complete platform. Unless your organization doesn't require the functionalities highlighted above, it is recommended to deploy the whole platform. 
```

Obviously, feel free to modify it :)

**Review by marcoam — CHANGES_REQUESTED** [review]
I left some comments on the "Conversation" section

**Comment by lena-larionova** [comment]
> 2. Perhaps, to avoid confusion it may make sense to change the URL:
>    https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/**install**-on-kubernetes/
>    to something like:
>    https://deploy-preview-2415--kongdocs.netlify.app/enterprise/2.1.x/deployment/installation/**kong**-on-kubernetes/

I'll change it, though I think the confusion will still occur, since we'll now have two URLs that sound almost the same:
`/kong-for-kubernetes` and `/kong-on-kubernetes`. Either way, it's just a temporary change until Shane and Co. do something to improve this naming...

**Comment by lena-larionova** [comment]
Borked branch rebase; closing PR, will reopen with a clean branch.

**Pull request closed without merging**
