### PR TITLE
Update url when filtering plugins

### PR DESCRIPTION
**Pull request by fabianrbz**
### Description

What did you change and why?
 
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3001)

Filter plugins based on the anchor and update the filters accordingly.

### Testing instructions

[All plugins](https://deploy-preview-5206--kongdocs.netlify.app/hub/)
[Konnect plugins](https://deploy-preview-5206--kongdocs.netlify.app/hub/#konnect)
[Third party](https://deploy-preview-5206--kongdocs.netlify.app/hub/#pub-not-konghq)

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by acgoldsmith** [comment]
@fabianrbz , this looks great - my only request is to rename the URL results from` /#konnect-cloud` to just `/#konnect` , please and thanks.

**Review by lena-larionova — COMMENTED** [review]
Should we do this for the subscription tiers as well (free, plus, enterprise)?

**Comment by fabianrbz** [comment]
subscription tiers fixed

**Review by lena-larionova — APPROVED** [review]
LGTM!

**Review by mheap — APPROVED** [review]

**Pull request merged**
