### PR TITLE
docs(hub): add kong-plugin-url-rewrite by stone-payments

### PR DESCRIPTION
**Pull request by biancarosa**
### Summary

This pull request adds our Kong plugin for more flexible URL rewriting capabilities.

### Full changelog

* Added kong-plugin-url-rewrite by stone-payments

### Issues resolved

N/A

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [x] Documentation 
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by coopr** [comment]
Thanks @biancarosa and sorry for my delay - reviewing now...

**Comment by biancarosa** [comment]
@coopr that's cool, it took us a while to open the PR too :)

**Comment by biancarosa** [comment]
@coopr any updates on this review? do we need to change something? :)

**Comment by levfishbluefish** [comment]
Sorry about the delay - I'll be taking over reviewing this. Will update shortly!

**Pull request merged**
