### PR TITLE
Update Kong Terraform Module for AWS

### PR DESCRIPTION
**Pull request by DennoVonDiesel**
For TD-539

Officially supported by Kong Inc. now.
Update version compatibility.
Add logo.

### CODE REVIEW

**Comment by h3xar0n** [comment]
On that note, should we set `enterprise: true` so that it appears under the Enterprise filter?

**Comment by DennoVonDiesel** [comment]
I checked the 1.3 changelog and my code would support it out of the box. What is the nomenclature  for the new EE versioning? 1.3.x ?

**Comment by levfishbluefish** [comment]
1.3-x

**Comment by DennoVonDiesel** [comment]
Feel free to merge at your convenience. I'm not able to.

**Comment by h3xar0n** [comment]
Thanks, @DennoVonDiesel

**Pull request merged**
