### PR TITLE
fixes #993

### LINKED ISSUE #993: Heading level CSS needs correction for H2 and H3
### Summary

H2 and H3 are currently visually indistinguishable:

basic_authentication_plugin___kong

### Steps To Reproduce

1. Visit https://docs.konghq.com/hub/kong-inc/basic-auth/
2. Inspect some headers - you'll notice that some of the have the same size+style, but are different heading levels

Note that this issue is apparent throughout the docs site, not just in the Hub.

### PR DESCRIPTION
**Pull request by knrt10**
### Summary

Hub Plugin heading level CSS corrected for H2 and H3

### Issues resolved

Fix #993

### Checklist:

- [x] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [ ] Documentation 
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by coopr** [comment]
Sorry, I think there was some misunderstanding. The issue is not that the heading levels are incorrect - they are correct. 

The issue is that the CSS styling applied to the heading levels results in H2 and H3 being visually indistinguishable. 

The correct fix is to adjust the CSS to cause H2 to be bigger/bolder than H3, so they are in the correct visual hierarchy.

**Comment by knrt10** [comment]
oh sorry my bad. Let me update the PR.

**Comment by coopr** [comment]
Hi @knrt10 I think you need to add your CSS commit to this PR.

Also note that as I was reviewing your previous work, I realized that this heading level styling issue affects all parts of the Docs site, not only the Hub - I updated the issue https://github.com/Kong/docs.konghq.com/issues/993 to clarify that. You can see an example of incorrect heading styling on this non-Hub page for example https://docs.konghq.com/0.14.x/cli/#available-commands

**Comment by coopr** [comment]
Solved by #1044

**Pull request closed without merging**
