### PR TITLE
DOCU-3348: Move search bar to topnav in home

### PR DESCRIPTION
**Pull request by fabianrbz**
### Description

What did you change and why?

[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3348)

Move search to topnav in landing page

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by lena-larionova** [comment]
Throwing this in here for a paper trail - talked on slack, other elements around the search bar are slightly off center, need slight adjustments:
Screenshot 2023-07-27 at 10 26 38 AM

**Comment by fabianrbz** [comment]
Nice catch! They should be aligned now

**Comment by fabianrbz** [comment]
Screenshot 2023-07-28 at 16 22 30

**Review by acgoldsmith — APPROVED** [review]
LGTM

**Pull request merged**
