### PR TITLE
minor update to Upstream TLS plugin page

### PR DESCRIPTION
**Pull request by marcoam**
Updating Upstream TLS plugin view to include instructions on how to add NGINX directives into Kong

### CODE REVIEW

**Comment by tlblessing** [comment]
@marcoam what would the direct review link be for this topic? I do not see Upstream TLS on the plugin hub at all. @lena-larionova ?

**Comment by marcoam** [comment]
Hey @tlblessing - you're correct that I am redirecting directly to the topic. Essentially, I want to make it easier for our customers/prospects to know how to accomplish the functionality that our plugin used to do in the nginx directives. 
I did this PR after a prospect mentioned that it would be useful to have more information on how to accomplish what the plugin used to do before it was deprecated!

**Comment by lena-larionova** [comment]
@tlblessing this topic is fine to update. The plugin is still reachable by its direct URL, so someone could find it by going to https://docs.konghq.com/hub/kong-inc/upstream-tls (or https://deploy-preview-2263--kongdocs.netlify.app/hub/kong-inc/upstream-tls/ for the preview). 

I don't think we'd want to remove it from the source - anyone using an older version of Kong might still need info on where to find out more about the plugin's replacement, or they might still be using the plugin in some version of Kong before 1.3.

**Comment by tlblessing** [comment]
> @tlblessing this topic is fine to update. The plugin is still reachable by its direct URL, so someone could find it by going to https://docs.konghq.com/hub/kong-inc/upstream-tls (or https://deploy-preview-2263--kongdocs.netlify.app/hub/kong-inc/upstream-tls/ for the preview).
> 
> I don't think we'd want to remove it from the source - anyone using an older version of Kong might still need info on where to find out more about the plugin's replacement, or they might still be using the plugin in some version of Kong before 1.3.

Thanks @lena-larionova and @marcoam for your guidance and PR.

**Pull request merged**
