### PR TITLE
[DOCU-3060] Add how to guide for customizing scopes and claims mappings.

### PR DESCRIPTION
**Pull request by haydenlam**
### Description
Preview documentation for OIDC customization options. This guide demonstrates how to:
- customize the list of scopes sent from the Konnect identity service to your IdP
- customize the mapping of required claim data to different claim values

This PR in present state is not intended to be merged since feature is still a work in progress. GA documentation may be an extension of this PR or replaced by a different one.
All credits go to @iamnande.

What did you change and why?
This PR is intended to generate preview link to share documentation with early adopters for feedback. 

### Testing instructions
No tests available as of this PR.

Netlify link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by cloudjumpercat** [comment]
Hi @haydenlam ! Thanks for opening this PR! Is this one ready for a writer review?

**Comment by haydenlam** [comment]
Hi @cloudjumpercat, this is early preview for a customer for some up coming features. I'll open a ticket for a formal review from docs. Thanks! 

For now, can we leave this PR up for a couple weeks?

**Comment by cloudjumpercat** [comment]
@haydenlam That works for me! When this is ready for a writer review, you can also add the "review:copyedit" label to it and that will let us know that it's ready to be reviewed. Thanks!

**Review by acgoldsmith — APPROVED** [review]
Approving for release by @haydenlam when he's ready

**Pull request merged**
