### PR TITLE
chore(deps): bump kumahq/kuma-website from 21c0852a to a0f63ea9

### PR DESCRIPTION
**Pull request by kong-docs**
Auto upgrade PR log:

a0f63ea9500dc41f7cca5f2716a0dca2dc72ce70 chore(deps): update docs from repo source (kumahq/kuma-website#1557)
43135e74a96abe04c9c69b6cc507bfa180920587 Move app/docs/raw to app/assets (kumahq/kuma-website#1558)
eaf9d9cc1183cf2131d6fd4ddacd1a4908033bed add some info about the GKE autopilot support (kumahq/kuma-website#1555)
079e6db3ebbf7d407c47b61b023a134a159592da Move raw files from `app/docs` to `app/assets/<version>/raw/`  (kumahq/kuma-website#1554)

### Description

Automated Kuma update that requires moving the static files from `app/mesh` to `app/assets` so that they are not processed by Jekyll.

### Testing instructions
Embedded files are rendered properly, e.g.
* [mesh changelog](https://deploy-preview-6686--kongdocs.netlify.app/mesh/changelog/)
* different policies: e.g. [traffic log](https://deploy-preview-6686--kongdocs.netlify.app/mesh/latest/policies/traffic-log/#all-policy-options), [mesh trace](https://deploy-preview-6686--kongdocs.netlify.app/mesh/latest/policies/meshtrace/#all-policy-options), etc
* I added redirects for the moved files 

Triggered by [action](https://github.com/Kong/docs.konghq.com/actions/runs/7269138600).
labels: skip-changelog,review:general

### CODE REVIEW

**Review by lahabana — APPROVED** [review]
The line deletion count is a little odd but I guess it'll go back to normal with the CI sync

**Comment by fabianrbz** [comment]
@lahabana that's because the [latest sync](https://github.com/Kong/docs.konghq.com/pull/6681) nested the files under `mesh/<version>/raw`.
I deleted the old ones and moved the ones under `raw` to `app/assets/mesh/<version>/raw`

**Comment by lahabana** [comment]
Ok makes sense!

**Comment by fabianrbz** [comment]
I added the missing redirects, the [changelog.md](https://github.com/Kong/docs.konghq.com/blob/main/changelog.md) linked to the files.
This should be ready now

**Review by mheap — APPROVED** [review]

**Pull request merged**
