### PR TITLE
Update installation options for Runtime Instances

### PR DESCRIPTION
**Pull request by d19dotca**
### Description

Updated the image and the text to reflect the latest iteration of Konnect's UI for installation options. Added ARM and Intel options for macOS as well, and separated by Standard & Advanced setup options based on Konnect's UI. 

I believe these changes to the Konnect UI took place a week ago, shortly after the[ last update I made](https://github.com/Kong/docs.konghq.com/pull/5948), so just keeping this in-line with the latest updates. :-)

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by Guaris — APPROVED** [review]

**Comment by lena-larionova** [comment]
I wonder - do we need the screenshot here anymore? I don't know that it's adding value now. Honestly, it might just cause more confusion, since this is the expanded menu and not the default view you get.

**Comment by lena-larionova** [comment]
Please don't merge this yet. This isn't live on prod for external users, only for konghq.com accounts.

**Comment by acgoldsmith** [comment]
@lena-larionova , good catch - thank you! This is first milestone of redesign that won't launch until Sept.

**Comment by lena-larionova** [comment]
@d19dotca I'm pulling this one into our Konnect Rename branch, as this change is planned to go live at the same time as the rename. Did a bit of housekeeping on the PR to make that happen.

**Pull request merged**
