### PR TITLE
DOCU-3306: Plugin Hub nav bar submenu

### PR DESCRIPTION
**Pull request by fabianrbz**
### Description

What did you change and why?
 
[Jira ticket](https://konghq.atlassian.net/browse/DOCU-3306)

Add submenu to Plugin Hub item in the top nav 

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by lena-larionova** [comment]
🤔 this is neat, but with the "Docs" dropdown being inconsistent, it's a bit jarring. Wonder if we can do something similar there? We should have descriptions of each product somewhere.

**Comment by lena-larionova** [comment]
at 1810px width and under (until it gets to mobile size), the navbar formatting gets a bit wonky:

Screenshot 2023-07-27 at 4 07 24 PM

**Comment by lena-larionova** [comment]
Could you also add the "View all" link from the Figma mockup?

Screenshot 2023-07-27 at 3 56 15 PM

**Comment by fabianrbz** [comment]
💯 I can do the same for `Docs`, do we have icons and descriptions for the different products?

**Comment by fabianrbz** [comment]
responsive

**Comment by lena-larionova** [comment]
> 💯 I can do the same for `Docs`, do we have icons and descriptions for the different products?

Sounds like Amy started a different ticket for that: https://konghq.atlassian.net/browse/DOCU-3367

**Comment by lena-larionova** [comment]
Re: the responsiveness, is there any way to make it shrink the gaps between entries instead of overflowing into a third row? On a small screen especially, like a 13in macbook, that menu ends up taking up most of the screen and is a bit jarring if you accidentally mouse over it.

Actually - to back up a little, maybe we should open the menus on click, not on mouseover, similar to our [main marketing site](https://konghq.com/customers). That's pretty standard, I think. And I think it'll be necessary as we add these huge menus.

**Comment by fabianrbz** [comment]
@lena-larionova I added the `onclick` behavior and the sub menu for the `Docs`
There's a new data file that lists the items in the submenu and the template just iterates over them

**Review by acgoldsmith — APPROVED** [review]
LGTM!

**Pull request merged**
