### PR TITLE
Add new distros, drop End-Of-Life distributions, and rename amazonlinux-2022 to 2023

### PR DESCRIPTION
**Pull request by fffonion**
### Description

What did you change and why?
 
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.

KAG-1551, KAG-1968

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by acgoldsmith** [comment]
@fffonion , can you please retarget to `release/gateway-3.4` rather than `main`? Thanks.

**Comment by fffonion** [comment]
@acgoldsmith Done : )  I haven't see `app/_data/tables/support/gateway/versions/34.yml` exist yet on this branch, is it expected?

**Review by teb510 — APPROVED** [review]
lgtm.

**Comment by fffonion** [comment]
@lena-larionova Thanks. I have included the changes for 3.4 version as well.

**Comment by lena-larionova** [comment]
@fffonion This commit re-adds Ubuntu 18.04 to everything before 3.4, with an EOL date: https://github.com/Kong/docs.konghq.com/pull/5770/commits/bd4872011c0d93ca5ccfb709faac473b2f7c7aa5

This basically covers our butts by saying that hey, we did support this, and we know packages exist ([which they do](https://download.konghq.com/gateway-3.x-ubuntu-bionic/pool/all/k/kong-enterprise-edition/)), but they have now reached EOL as of April 2023.

**Comment by kikito** [comment]
@lena-larionova @fffonion will be OOO until next monday (July 31st)

**Comment by lena-larionova** [comment]
> fffonion will be OOO until next monday (July 31st)

We should be good on this PR now - I get what he was going for, so I just took the diplomatic docs approach to do the same 😄

**Review by lena-larionova — APPROVED** [review]
LGTM - if there's an issue with the last change I made, we can fix after you get back @fffonion . Merging to unblock some other work.

**Comment by fffonion** [comment]
Thank you for taking care of this @lena-larionova @kikito !

**Pull request merged**
