### PR TITLE
Clarify cookie_samesite None for Sessions plugin

### PR DESCRIPTION
**Pull request by tlblessing**
https://konghq.atlassian.net/browse/DOCS-1324

DOCS-1324 Document interdependency for Session Plugin cookie_samesite None and cookie_secure true

Added verbiage recommended by @aaronhmiller to description:

`None` requires the Secure attribute in latest browser versions.

Direct review link:

https://deploy-preview-2334--kongdocs.netlify.app/hub/kong-inc/session/

Updates:

image

Make live links:

image

### CODE REVIEW

**Comment by aaronhmiller** [comment]
Just what the "doc"tor ordered! Thank you @tlblessing this bit a few of us recently and it's GREAT to see it documented so well.

**Review by aaronhmiller — APPROVED** [review]
Love it. Thanks!

**Comment by tlblessing** [comment]
> Love it. Thanks!

Thank you @aaronhmiller ! @GayleNeumann or @lena-larionova, can I please get a docs approval so I can merge?

**Review by GayleNeumann — APPROVED** [review]
LGTM

**Pull request merged**
