### PR TITLE
feat(opentelemetry): propagate GCP trace header

### PR DESCRIPTION
**Pull request by jonabc**
### Description

What did you change and why?
 
Documentation updates for https://github.com/Kong/kong/pull/11254

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by lena-larionova — COMMENTED** [review]
LGTM but not approving yet, since the parallel eng PR isn't merged. Will merge when that's done.

**Comment by jonabc** [comment]
@lena-larionova :wave: the linked PR was approved and merged, but it looks like this won't make it in until 3.5.x.  I updated the changelog with a 3.5.x section but this is still targeting the `release/gateway-3.4` branch because there's not a release branch yet for 3.5.  Any advice on how to get this ready for 3.5?

**Comment by jonabc** [comment]
yikes, setting the base branch to `release/gateway-3.5` caused a bit of chaos.  I cherry-picked my commit onto the release-3.5 branch, changed checks and references in the commit from 3.4 to 3.5, and force pushed.

**Review by lena-larionova — APPROVED** [review]
LGTM - sorry that you had to go through all that trouble for such a small docs change. Appreciate the effort!

**Comment by lena-larionova** [comment]
(please ignore the failing tests, the linked submodule hasn't been updated, but that has nothing to do with this PR)

**Pull request merged**
