### PR TITLE
Plugin hub single source demo

### PR DESCRIPTION
**Pull request by mheap**
### Summary
This is a preview PR to show how single sourced plugin docs can work.

> **DO NOT MERGE**

This PR adds a new `Demo` plugin that has 5 releases across 3 major versions.

* Versions `0.1.x` and `0.2.x` use the old style documentation where each version has a new markdown file
* Versions `1.0.x` and `1.1.x` are single sourced from `_1.x.md`
* Version `2.0.x` falls back to the default file of `_index.md`

Single sourcing input files start with an underscore to prevent Jekyll processing them directly.

Interesting features:

* Parameters can have a `minimum_version` and `maximum_version` field ([sample](https://github.com/Kong/docs.konghq.com/commit/521218b932545e2593547f3aa160586cdd8987d3#diff-0e0c800f13848e118ba66dbbff25bd3c86b7d2a97334e0f908449d0678e91631R56))
* Content can be [conditionally rendered](https://github.com/Kong/docs.konghq.com/commit/521218b932545e2593547f3aa160586cdd8987d3#diff-0e0c800f13848e118ba66dbbff25bd3c86b7d2a97334e0f908449d0678e91631R63-R69)

The PR that will be merged for this work can be found [here](https://github.com/Kong/docs.konghq.com/pull/3836). This PR **should not be merged** and only serves as a way to show the potential features and view the final rendered result in a preview app

There are a lot of changes as this also includes the single sourcing generator PR. I'd recommend looking at [this commit](https://github.com/Kong/docs.konghq.com/pull/3837/commits/521218b932545e2593547f3aa160586cdd8987d3) specifically to see the plugin data only changes.

### CODE REVIEW

**Comment by kikito** [comment]
I think this change makes a lot of sense. It would definitively make things easier to maintain -- less duplication of files per plugin.

Would it be possible to keep using `index.md` if it exists? (Otherwise, use `_index.md`). That would sidestep having to rename of those indexes to _index right away.

**Comment by Guaris** [comment]
> I think this change makes a lot of sense. It would definitively make things easier to maintain -- less duplication of files per plugin.
> 
> Would it be possible to keep using `index.md` if it exists? (Otherwise, use `_index.md`). That would sidestep having to rename of those indexes to _index right away.

That might make it harder to enforce the standard though.

**Review by Guaris — APPROVED** [review]

**Comment by mheap** [comment]
> Would it be possible to keep using index.md if it exists? (Otherwise, use _index.md). That would sidestep having to rename of those indexes to _index right away.

Unfortuanately not. Jekyll processes anything that doesn't start with a `_` so we need to rename the file and let the single sourcing generator take care of writing it out.

There should be no change in behaviour - the file is now called `_index.md` rather than `index.md` but it works exactly as it did before unless you use any of the conditional rendering functionality

**Comment by mheap** [comment]
Closing as #3836 looks close to merge

**Pull request closed without merging**
