### PR TITLE
Feat: Ubuntu 24.04 (Noble Numbat)

### PR DESCRIPTION
**Pull request by curiositycasualty**
### Description

This PR changes the Ubuntu gateway install docs to makes the latest and greatest Ubuntu, 24.04 aka "Nobel Numbat", the default ubuntu flavor displayed alongside the install instructions.

### Testing instructions

Preview link: https://deploy-preview-7471--kongdocs.netlify.app/

### Checklist 

- [x] Review label added 
- [x] [Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.

~~🚧 This PR should NOT be merged before both [the OSS PR](https://github.com/Kong/kong/pull/13626), and a forthcoming EE port PR are merged. 🚧~~

### CODE REVIEW

**Comment by AndyZhang0707** [comment]
Hi @isa, I would also expect an update to the os support matrix as shown in the page: https://docs.konghq.com/gateway/latest/support-policy/

**Comment by lena-larionova** [comment]
@mheap do we want to make this new flavor the default, or leave Jammy as the most commonly used one? Based on the recent issues that a customer ran into, we shouldn't change this lightly.

**Comment by mheap** [comment]
Good question. @curiositycasualty can you test installing the Numbat package on older OSes? If it's good on everything since Jammy we can update the default

**Comment by curiositycasualty** [comment]
Rumored released dates for 24.04.1 are: mid/15th of August.

**Comment by curiositycasualty** [comment]
@mheap @lena-larionova This is finally ready for review.

Noble support did NOT make it into 3.8-- it is currently on `master` for both gateway repos. So this PR (copies and) updates the 3.9 version table and include "greater than" logic in the ubuntu gateway install page. Which is where I expect Noble support to land: in 3.9.

@AndyZhang0707 The 39 version table file that is part of this PR will update the support matrix page when that becomes the "latest" gateway version in the docs.

**Comment by curiositycasualty** [comment]
Scratch that, missed something 🙄

**Comment by curiositycasualty** [comment]
@mheap @lena-larionova This is finally ready for review.

Noble support did NOT make it into 3.8-- it is currently on `master` for both gateway repos. So this PR (copies and) updates the 3.9 version table and include "greater than" logic in the ubuntu gateway install page. Which is where I expect Noble support to land: in 3.9.

@AndyZhang0707 The 39 version table file that is part of this PR will update the support matrix page when that becomes the "latest" gateway version in the docs.

**Review by lena-larionova — APPROVED** [review]

**Pull request merged**
