### PR TITLE
[DOCU-1837] Fix broken links

### PR DESCRIPTION
**Pull request by lena-larionova**
### Summary
* Fixing various broken links in the docs
* Based on the report, adding redirects for common errors and broken links that live outside the doc site
* Enabling the link checker to test `/hub/` and `/community/` links - most of the reported broken links are for `/hub/`, and for whatever reason, we have that disabled. 
  * Ran the link checker locally after enabling it on `/hub/`, caught a bunch more broken links, fixed those

Note to reviewers: the jekyll `redirect_from` plugin does not work on plugin index pages, and should never be used in plugins (it shouldn't really be used anywhere, but that's a bigger/separate issue).

### Reason
Marketing team gave us a broken link report.

### Testing
Spot-check some link fixes and redirects, eg:

https://deploy-preview-3225--kongdocs.netlify.app/hub/kong-inc/basic-authentication - redirects to basic-auth
https://deploy-preview-3225--kongdocs.netlify.app/hub/kong-inc/ldap-authentication-advanced - redirects to ldap-auth-advanced
https://deploy-preview-3225--kongdocs.netlify.app/admin-api/ - redirects to gateway OSS Admin API doc

### CODE REVIEW

**Review by falondarville — COMMENTED** [review]
I get a 404 for this page: https://deploy-preview-3225--kongdocs.netlify.app/hub/kong-inc/ldap-authentication

**Comment by falondarville** [comment]
> Note to reviewers: the jekyll `redirect_from` plugin does not work on plugin index pages, and should never be used in plugins (it shouldn't really be used anywhere, but that's a bigger/separate issue).

This is a great opportunity to open an Issue to rm the plugin.

**Comment by lena-larionova** [comment]
> > Note to reviewers: the jekyll `redirect_from` plugin does not work on plugin index pages, and should never be used in plugins (it shouldn't really be used anywhere, but that's a bigger/separate issue).
> 
> This is a great opportunity to open an Issue to rm the plugin.

Issue or ticket? This is unfortunately a pretty big undertaking, as you'd have to:
1. Remove the `redirect_from` value from all files that use it (there's a lot).
2. Fix all links that were being redirected (for whatever reason, maintainers used to just set up redirects and never update links, so we have a _ton_ of legacy links floating around).
3. Figure out which redirects we do still need to keep and add them to `app/_redirects`.
3. Uninstall plugin.

And yes, I've thought this through before, why do you ask? 😄

**Comment by lena-larionova** [comment]
> I get a 404 for this page: https://deploy-preview-3225--kongdocs.netlify.app/hub/kong-inc/ldap-authentication

That would be because I pasted the wrong one 🤦‍♀️  It's actually https://deploy-preview-3225--kongdocs.netlify.app/hub/kong-inc/ldap-authentication-advanced that redirects to ldap-auth-advanced. But I'll add a redirect for that one as well, as people tend to try the full plugin name as the link.

**Review by falondarville — APPROVED** [review]
LGTM

**Pull request merged**
