### PR TITLE
docs(gateway-oss) update load balancer  description

### PR DESCRIPTION
**Pull request by locao**
Also, a lot of ending spaces were auto-removed.

### CODE REVIEW

**Comment by lena-larionova** [comment]
Just an FYI, this doc is autogenerated from kong/kong. Can you also update the source file at https://github.com/Kong/kong/blob/master/autodoc/admin-api/data/admin-api.lua?

**Comment by locao** [comment]
Thank you, @lena-larionova! I opened this PR Kong/kong#7098, can you check it, please?

**Comment by lena-larionova** [comment]
@locao do you want to just copy over the changes you made in kong/kong to this PR so you don't need to regenerate the whole file?

**Comment by locao** [comment]
> @locao do you want to just copy over the changes you made in kong/kong to this PR so you don't need to regenerate the whole file?

Done, thanks!

**Review by Bradamant3 — APPROVED** [review]
Per conversation, LGTM. @lena-larionova do we have a way to automatically copy/move the generated file so we don't make a habit of manually copying changes?

**Pull request merged**
