### PR TITLE
feat: add filter chains to Admin OSS spec

### PR DESCRIPTION
**Pull request by hishamhm**
### Description

Added WebAssembly Filter Chain endpoints to OSS Admin API spec, matching those from Admin-EE docs. (see #6829).

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] ~[Conditional version tags](https://docs.konghq.com/contributing/conditional-rendering/#conditionally-render-content-by-version) added, if applicable.~ changes done to `/latest/`.

### CODE REVIEW

**Comment by hishamhm** [comment]
Even though I added  the same entries from Admin-EE into [api-specs/Gateway-OSS/latest/kong-oss.yaml](https://github.com/Kong/docs.konghq.com/pull/7387/files#diff-c23fd80c90e140b22900139b778ff6541078ca183ed960d49249fdcf802353de), the Filter Chains docs did not show up in the Netlify preview: https://deploy-preview-7387--kongdocs.netlify.app/gateway/api/admin-oss/latest/#/filter-chains/get-filter-chains

Am I missing something? :thinking:

**Comment by Guaris** [comment]
> Even though I added the same entries from Admin-EE into [api-specs/Gateway-OSS/latest/kong-oss.yaml](https://github.com/Kong/docs.konghq.com/pull/7387/files#diff-c23fd80c90e140b22900139b778ff6541078ca183ed960d49249fdcf802353de), the Filter Chains docs did not show up in the Netlify preview: https://deploy-preview-7387--kongdocs.netlify.app/gateway/api/admin-oss/latest/#/filter-chains/get-filter-chains
> 
> Am I missing something? 🤔

Yes, the specs have to be uploaded as API product documentation to the org's konnect organization.

**Comment by hishamhm** [comment]
> Yes, the specs have to be uploaded as API product documentation to the org's konnect organization.

@Guaris ah, thanks for the clarification! I don't think I have access to that. Is this something the docs-maintainers handle after this is reviewed and merged?

**Comment by Guaris** [comment]
> > Yes, the specs have to be uploaded as API product documentation to the org's konnect organization.
> 
> @Guaris ah, thanks for the clarification! I don't think I have access to that. Is this something the docs-maintainers handle after this is reviewed and merged?

Absolutely!

**Review by Guaris — DISMISSED** [review]

**Review by Guaris — APPROVED** [review]

**Comment by Guaris** [comment]
LGTM
https://docs.konghq.com/gateway/api/admin-oss/latest/#/filter-chains/get-filter-chains

**Pull request merged**
