### PR TITLE
Add OSS/EE toggle in sidebar for install topics

### PR DESCRIPTION
**Pull request by mheap**
### Summary
Add the ability to toggle between OSS/EE installation instructions in the sidebar by using `navtabs_ee` rather than `navtabs`

You can specify `?install=oss` in the URL to default to OSS installation instructions

We need a new icon for the Enterprise/OSS switcher, but that should be the only outstanding issue

### Testing

* [Install on RHEL (Default, EE)](https://deploy-preview-3807--kongdocs.netlify.app/gateway/2.8.x/install-and-run/rhel/)
* [Install on RHEL (With OSS flag)](https://deploy-preview-3807--kongdocs.netlify.app/gateway/2.8.x/install-and-run/rhel/?install=oss)

### CODE REVIEW

**Comment by lena-larionova** [comment]
> We need a new icon for the Enterprise/OSS switcher, but that should be the only outstanding issue

Done in https://github.com/Kong/docs.konghq.com/pull/3807/commits/866e2eb95130707dac77e161b729581797bd4769.

**Comment by lena-larionova** [comment]
Can you add a couple of lines about this changes to the tabs section of our contributing guide?
https://github.com/Kong/docs.konghq.com/blob/oss-ee-toggle/app/contributing/markdown-rules.md

**Comment by lena-larionova** [comment]
LGTM for the toggle functionality with navtabs, if that's the intended scope of this PR.

I wonder if we can extend this a bit more, however. There are a bunch of sections of the page labelled as `enterprise` or `free` (dev portal, license, manager, etc). Can we also set a conditional on them, eg a `{% if kong_ee %}` tag? For example, nearly everything on this page from super admin onwards is for EE users: https://deploy-preview-3807--kongdocs.netlify.app/gateway/2.8.x/install-and-run/rhel/

**Review by lena-larionova — APPROVED** [review]
Didn't realize that I wrote LGTM without an actual approval, apologies.

**Comment by mheap** [comment]
We can expand this to hide the enterprise only features, but I'd like to check if that's desired behaviour. We might want to show the content but flag as enterprise on OSS views to show what's available

**Comment by mheap** [comment]
@lena-larionova @Guaris I've updated all of the installation topics in 2.8 to use the new `navtabs_ee` functionality, and have removed the direct links to the packages as requested.

I also changed the phrasing on the index from `not-OSS` to `Enterprise Free`.

Please review when you can. We'd like to release this on Tues/Weds

**Comment by lena-larionova** [comment]
> have removed the direct links to the packages as requested.

Out of curiousity - where did this request come from? The original request to add the links at the top of install pages came from marketing, they should be made aware if we're removing the links.

**Comment by lena-larionova** [comment]
One small thing: for codeblocks with hidden tabs, the copy-code icon floats above the codeblock:

Screen Shot 2022-04-18 at 2 42 18 PM

**Comment by mheap** [comment]
> Out of curiousity - where did this request come from? The original request to add the links at the top of install pages came from marketing, they should be made aware if we're removing the links.

Dragos is looped in on this and hasn't raised any concerns

RE: Code blocks, I'll take a look but this can be a followup imo if we need to push this week.

**Review by lena-larionova — APPROVED** [review]
Dragos was the one that asked for the link blocks originally, so if he's good, then LGTM 😄

**Comment by lena-larionova** [comment]
https://deploy-preview-3807--kongdocs.netlify.app/gateway/2.8.x/install-and-run/rhel/ - if you switch to the YUM repository tab, the Kong Gateway/Kong Gateway OSS tabs are still there.

**Comment by mheap** [comment]
> Hmm. I'm not a huge fan of this approach. It looks like an error, especially since the regular code blocks don't look like this.

Should they look like this? Having the icon overlap the text looks odd to me too

image

**Comment by lena-larionova** [comment]
> Should they look like this? Having the icon overlap the text looks odd to me too

I agree - but at least it's consistent for now. That's a separate issue that I've been wanting to deal with but keep forgetting about.

**Comment by mheap** [comment]
@lena-larionova Went back and did it "properly". The code snippets should now look like all other snippets and no longer have the thicker top border

**Pull request merged**
