### PR TITLE
pdk kong.plugin.get_id()

### PR DESCRIPTION
**Pull request by StarlightIbuki**
### Description

We added a PDK function to get the plugin's ID: FTI-4019

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by lena-larionova** [comment]
Based on the comments in this PR, looks like this didn't make it into 3.2 and is going into 3.3. Can you please point your PR to the `release/gateway-3.3` branch?

**Comment by StarlightIbuki** [comment]
@lena-larionova As the comment in the file suggests, and the GitHub bot notices with a tag, should we close this and wait for auto-generating scripts to do the job?

**Comment by lena-larionova** [comment]
@StarlightIbuki yeah - apologize, I didn't see which file you had edited. You're right, that page will get autogenerated.

Do you think that this new module fits anywhere in the plugin development guide (anything under https://docs.konghq.com/gateway/latest/plugin-development/) ? How would you expect someone to use this module?

**Comment by StarlightIbuki** [comment]
> @StarlightIbuki yeah - apologize, I didn't see which file you had edited. You're right, that page will get autogenerated.
> 
> Do you think that this new module fits anywhere in the plugin development guide (anything under https://docs.konghq.com/gateway/latest/plugin-development/) ? How would you expect someone to use this module?

Sorry, I was not available last week.
Yes, it should be mentioned in `plugin-development`. The function is used to identify an instance of a plugin, so we can for example create a memory cache for instance-level status (like what we did with `__key__`).

Closing this PR as it's not needed.

**Pull request closed without merging**
