### PR TITLE
docs(src) Update wording for ingress controller, decK, and update LICENSE year

### PR DESCRIPTION
**Pull request by ArjunSharda**
### Summary

This will update the wording of the ingress controller MD files and decK MD files and update the License year of Kong from 2015-2020 to 2015-2022.

### Reason

Helps with grammar and changes the LICENSE year

### Testing

Check for grammar accuracy

Needs review:copyedit label

### CODE REVIEW

**Comment by mheap** [comment]
Hi @ArjunSharda, thank you for your contribution.

If you're contributing in order to qualify for the Kong Summit hackathon, I'm afraid this contribution does not meet the eligibility criteria. Documentation changes must be substantial to qualify.

If you'd like to discuss a larger contribution, please open an issue in this repo and we can work out how best to support you in your work

**Comment by ArjunSharda** [comment]
How substantial do you mean? Do you mean code contributions?

**Comment by ArjunSharda** [comment]
@mheap

**Comment by gAmUssA** [comment]
@ArjunSharda 

> How substantial do you mean? 

It can be something like missing part of some component or plugin. Or it can be getting started guide for some integration. 
More «substantial» than typos and rephrasing. 
Hope it makes sense

**Pull request closed without merging**
