### PR TITLE
Add new konnect cta to docs

### PR DESCRIPTION
**Pull request by fabianrbz**
### Description

What did you change and why?
 
[Related Jira ticket](https://konghq.atlassian.net/browse/DOCU-3290)

Add a new CTA for driving people to Konnect, checking whether customers dismiss it or follow it.

This is only rendered in:
* app/_src/gateway/index.md
* app/_src/gateway/install/docker/index.md

It sets a cookie (`konnect-cta-card`) to keep track of whether the overlay was dismissed or clicked, so we don't show it to customers again

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by acgoldsmith** [comment]
@fabianrbz thanks for preview to see how this behaves. Do we have another option to locate besides the left menu? 

On both pages, when I scroll to the bottom of the page, the CTA is still obscured because the left menus are very long.

**Comment by fabianrbz** [comment]
@acgoldsmith we can, I was following the example.
we could place it at the top of the menu, do you think that would work?

**Comment by acgoldsmith** [comment]
@fabianrbz thanks for suggestions, as we discussed, let's try to add as overlay in the bottom left of the screen... I think that location is good for distance from CTA button in top nav, and preferable to the other options you've outlined.

**Comment by fabianrbz** [comment]
@acgoldsmith I added the overlay but had to center the modal, otherwise it looked too weird. Is that ok?
cta-modal

**Comment by acgoldsmith** [comment]
> @acgoldsmith I added the overlay but had to center the modal, otherwise it looked too weird. Is that ok? cta-modal

Let's move the overlay to bottom right corner so it's not obscuring the page content, please and thanks

**Comment by acgoldsmith** [comment]
@fabianrbz , let's make some additional tweaks, please:

remove the grey from page behind overlay
narrow down the size of the overlay window so it's about the same width as the left nav
when I click the close X there's a second step I have to click for "skip to content" - is it possible to remove this?
Screenshot 2023-08-24 at 8 41 32 AM

**Comment by mheap** [comment]
> remove the grey from page behind overlay

Checking the preview today I think what we had yesterday with the wider CTA + grey background was more inline with what's expected (very obvious, but easy to dismiss)

**Comment by acgoldsmith** [comment]
Okay, @fabianrbz let's go back to the more obvious version as Michael suggests and call it good. Thanks

**Review by acgoldsmith — APPROVED** [review]
LTGM

**Pull request merged**
