### PR TITLE
feat(conf) Adding documentation for keepalive disable

### PR DESCRIPTION
**Pull request by pryorda**
### Summary

Adding docs for [kong:3716](https://github.com/Kong/kong/pull/3716l)

### Full changelog

* Added docs for keepalive disable

### Checklist:

- [Y] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked
- [Y] Documentation
- [Y] Spellchecked my updates:
- [IDK] Ready to be merged <

First PR on docs. Lemmeno if I missed anything.

### CODE REVIEW

**Comment by thibaultcha** [comment]
@coopr There will be a point at which we will derive a `release/{next version}` branch out of the current master branch (when the timing is right), and which point, we will cherry pick this patch into the release branch, and open a PR from the release branch into the master branch, which will be long-lived until the release is cut and the website deployed. Those PRs that are currently pending like this one, receive the `release` GitHub label

**Comment by coopr** [comment]
Thanks for the education @thibaultcha , much appreciated!

**Comment by thibaultcha** [comment]
@pryorda In 1.0, of which rc3 sais released yesterday.

**Comment by pryorda** [comment]
Awesome, Thanks.

**Comment by levfishbluefish** [comment]
@pryorda 1.0 docs are now available. Can you move this update to the 1.0 configuration file vs the 0.14?

**Comment by pryorda** [comment]
As in rebase off master?

**Comment by pryorda** [comment]
@levfishbluefish Should be good to go.

**Pull request merged**
