### PR TITLE
[DOCU-2140] Admin API: Remove wording about cannot delete/modify

### PR DESCRIPTION
**Pull request by falondarville**
### Summary

Remove wording in Admin API docs Target Object that says targets cannot be modified or deleted.

### Reason

Addresses [DOCU-2140](https://konghq.atlassian.net/browse/DOCU-2140)

### Testing

https://deploy-preview-3663--kongdocs.netlify.app/gateway/2.7.x/admin-api/#target-object

### CODE REVIEW

**Comment by falondarville** [comment]
Link error is a false positive, corroborated with @lena-larionova

**Review by lena-larionova — APPROVED** [review]
LGTM

Since this doc is autogenerated, please open a PR in kong/kong to update the source file as well: https://github.com/Kong/kong/blob/master/autodoc/admin-api/data/admin-api.lua#L1609-L1611

**Comment by falondarville** [comment]
Kong/kong corresponding change: https://github.com/Kong/kong/pull/8413

**Comment by mheap** [comment]
@falondarville  Can we backport this change to all versions since 2.2.0?

**Pull request merged**
