### PR TITLE
add compatibilities for kong 3.2

### PR DESCRIPTION
**Pull request by randmonkey**
### Description

What did you change and why?
 
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.

- Add compatibility matrix for Kong 3.2 with KIC versions.
- Add compatibility status with different router flavors of Kong 3.2.

### Testing instructions

Netlify link: 
version compatibility page: https://deploy-preview-5267--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/version-compatibility/
Supported Kong Router Flavors page: https://deploy-preview-5267--kongdocs.netlify.app/kubernetes-ingress-controller/latest/references/supported-router-flavors/

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by acgoldsmith — APPROVED** [review]
LGTM

**Comment by acgoldsmith** [comment]
@randmonkey , apologies for the delayed review. 

there's a conflict on app/_src/kubernetes-ingress-controller/guides/using-gateway-discovery.md created by the 2.9 release that I'm flagging for you to resolve, please.

**Comment by lena-larionova** [comment]
@pmalek @randmonkey checking back in, is this still needed?

**Comment by pmalek** [comment]
> @pmalek @randmonkey checking back in, is this still needed?

I believe this got outdated pretty severely at this point. IIRC this was about 3.2 compatibility https://github.com/Kong/docs.konghq.com/blob/main/app/_src/kubernetes-ingress-controller/references/version-compatibility.md which already is updated.

This might be closed. If @randmonkey feels there's something else to cover here feel free to reopen and comment.

**Pull request closed without merging**
