### PR TITLE
Feat: Add tool that detects broken markdown anchors

### PR DESCRIPTION
**Pull request by mheap**
### Description

Add a new tool that detects output of ` [.+][.+] ` in the `dist` folder. These are markdown links where the anchor at the bottom of the file could not be found.

#6101 is a good example of where this happens

### Testing instructions

Preview link: N/A

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by mheap** [comment]
This PR will fail until the broken links are fixed. I don't have time to work through them right now, so if anyone else beats me to it please feel free to push to this PR

**Comment by lena-larionova** [comment]
Ran it locally and fixed everything that came up.

**Comment by lena-larionova** [comment]
Re: the three individual vale commits. For some reason, vale keeps checking only one file in the PR, so every time I made a commit, it checked a different file and I guess stopped once it found a file with issues?

Yet one more thing for @Guaris to fix when he gets the chance to look at vale (maybe disabling reviewdog will help here too).

**Comment by lena-larionova** [comment]
Failed as it should - check is working now:
Screenshot 2023-09-27 at 3 49 04 PM

**Review by lena-larionova — APPROVED** [review]

**Pull request merged**
