### PR TITLE
fix(proxy-reference) add missing reference link

### PR DESCRIPTION
**Pull request by Tieske**

### CODE REVIEW

**Comment by Tieske** [comment]
direct link to the fixed link in the preview: https://deploy-preview-2142--kongdocs.netlify.app/2.0.x/proxy/#4-errors--retries

**Comment by Tieske** [comment]
@lena-larionova sorry I missed you comment somehow, search & replace on all of them done.

**Comment by Tieske** [comment]
btw; don't we have a linter that finds broken links like this?

@hutchic were you also involved with that?

**Comment by lena-larionova** [comment]
> btw; don't we have a linter that finds broken links like this?
> 
We do but it doesn't seem to catch these links, for whatever reason.

**Comment by hutchic** [comment]
it doesn't catch external links or anchors

**Pull request merged**
