### PR TITLE
fix: Fallback Service for requests

### PR DESCRIPTION
**Pull request by Rajakavitha1**
### Description

tested, and validated the guide end to end works as expected.

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by mheap — CHANGES_REQUESTED** [review]
This guide is missing Gateway API examples. Please work with #team-k8s to add them

**Comment by mheap** [comment]
@Rajakavitha1 Please remove the file + item from the 3.0 navigation in this PR

**Comment by Rajakavitha1** [comment]
@mheap just removed it from the nav. Please take a look.

**Comment by mheap** [comment]
@Rajakavitha1 We can delete the file in `app/_src` too if we no longer need it

**Review by mheap — APPROVED** [review]

**Pull request merged**
