### PR TITLE
fix: `my-secret-value` example letter case in Gateway secrets management docs

### PR DESCRIPTION
**Pull request by muthugomu-kong**
The variable was in UPPER CASE and UNDERSCORE, changed it to lowercase and hypen

### Testing instructions

Preview link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by mheap** [comment]
@muthugomu-kong Can you tell us more about this change? The uppercase with underscores format is expected to work

**Review by cloudjumpercat — APPROVED** [review]
LGTM! Thanks for making this update!

**Comment by muthugomu-kong** [comment]
> LGTM! Thanks for making this update!

@cloudjumpercat The instructions documented at https://docs.konghq.com/gateway/3.4.x/kong-enterprise/secrets-management/backends/env/ is working as expected, it was my mis-understand that the variable must be referred with correct case in VAULT as well, however I understand that UPPERCASE and UNDERSCORES used in the environment variables are being referred in vault as lowercase and hyphen. May be a small note could be added stating that "UPPERCASE and UNDERSCORES used in the environment variables will be referred in vault as lowercase and hyphen only" so customers are clear.

Kindly rollback this change.

**Comment by cloudjumpercat** [comment]
Documentation works as written, so closing this PR.

**Pull request closed without merging**
