### PR TITLE
Fix breadcrumb links

### PR DESCRIPTION
**Pull request by mheap**
### Summary
Link all segments in the breadcrumbs to the overview page for that section. The segment is only linked in the URL exists, and is presented without a link if it would lead to a 404.

The breadcrumbs expect the overview page to be named `index.md` within a folder (e.g. /gateway/3.0.x/kong-enterprise/). It does NOT work if the file is named `overview.md` (e.g. /gateway/3.0.x/kong-production/deployment-topologies/overview/). We should standardise on our overview URLs, and I'd vote for not having `/overview/` explicitly in the URL

### Reason
The new IA work has created nested subdirectories. This highlights that breadcrumb links are working incorrectly:

### Testing
Try any nested URLs in the review app

### CODE REVIEW

**Comment by cloudjumpercat** [comment]
@mheap I'm not sure if it's working as expected, or at least as I expected. Ex. when I go to [this page](https://deploy-preview-4269--kongdocs.netlify.app/gateway/3.0.x/kong-production/licenses/access-license/), I can't click "Kong production" or "Licenses" in the breadcrumbs at the top of the page. I can click "Kong Gateway" and "Home" in the breadcrumbs though.

**Comment by mheap** [comment]
@cloudjumpercat That's a review app for a different PR. Check this one https://deploy-preview-4271--kongdocs.netlify.app/gateway/3.0.x/kong-production/licenses/access-license/

**Review by cloudjumpercat — CHANGES_REQUESTED** [review]
Looks like breadcrumbs are clickable for all but the following sections:

- Kong in Production
- Kong Manager
- Reference

Other than that, overview.md pages are displaying the correct breadcrumbs on those pages, so that looks correct.

**Comment by mheap** [comment]
The items listed above don't have any index page, so they're not expected to be clickable.

e.g. https://deploy-preview-4271--kongdocs.netlify.app/gateway/3.0.x/kong-manager/overview/ needs moving to https://deploy-preview-4271--kongdocs.netlify.app/gateway/3.0.x/kong-manager/ for it to become clickable

**Comment by mheap** [comment]
Additional question: Would you expect the overview files to be moved in this PR, or as a followup?

**Comment by cloudjumpercat** [comment]
> The items listed above don't have any index page, so they're not expected to be clickable.

Ah, okay, that makes sense. 

> Additional question: Would you expect the overview files to be moved in this PR, or as a followup?

I think either would be okay. We could do it as a 3.0 QA task.

**Review by cloudjumpercat — APPROVED** [review]

**Pull request merged**
