### PR TITLE
Docs/ee proxy cache rate limiting redis ssl

### PR DESCRIPTION
**Pull request by murillopaula**
Most important commits are

https://github.com/Kong/docs.konghq.com/pull/2408/commits/e5f109eef251c999431a230c883b512bc7c0ea3b
https://github.com/Kong/docs.konghq.com/pull/2408/commits/dbdab1372dbedd7539f4677b4e980861661ecedd

The rest is just updating indexes and versions.

### CODE REVIEW

**Comment by murillopaula** [comment]
Let me know if I did the right thing with the plugin versions and indexes. Version format of both plugins are different.

- proxy-cache-advanced does not have a version: https://docs.konghq.com/hub/kong-inc/proxy-cache-advanced/
  - I created just the 2.1-x.md version that does not include the new information and updated  the current index that does include it

- rate-limiting-advanced has a 1.3 latest version only: https://docs.konghq.com/hub/kong-inc/rate-limiting-advanced/
  - I created the 1.3-x.md, 1.5-x.md and 2.1-x.md versions that does not include the new information and updated the current index that does include it

**Comment by tlblessing** [comment]
Thank you for working on this @murillopaula. I had logged https://konghq.atlassian.net/browse/DOCS-1363 about these issues.
I'll review.

**Comment by tlblessing** [comment]
> Let me know if I did the right thing with the plugin versions and indexes. Version format of both plugins are different.
> 
> * proxy-cache-advanced does not have a version: https://docs.konghq.com/hub/kong-inc/proxy-cache-advanced/
>   
>   * I created just the 2.1-x.md version that does not include the new information and updated  the current index that does include it
> * rate-limiting-advanced has a 1.3 latest version only: https://docs.konghq.com/hub/kong-inc/rate-limiting-advanced/
>   
>   * I created the 1.3-x.md, 1.5-x.md and 2.1-x.md versions that does not include the new information and updated the current index that does include it

So the most current version (2.1.x) would be the index file. I'll check out your branch and make the corrections.

**Comment by tlblessing** [comment]
We will close this PR and make updates in the private repo for the upcoming release.

Associate DOC tickets with:

https://konghq.atlassian.net/browse/FTI-1638
https://konghq.atlassian.net/browse/FTI-1639

**Comment by tlblessing** [comment]
Will make new PRs on 2.2 repo.

**Pull request closed without merging**
