### PR TITLE
Making the error page fun

### PR DESCRIPTION
**Pull request by Sayanta66**
### Summary

Added a sad Kong Gif on the error page. It will display a fun gif whenever a person gets a 404 error.

### Reason

Issue #3154

### CODE REVIEW

**Comment by ArmanChand** [comment]
@Sayanta66 
Please don't hijack tickets assigned to others. 
@lena-larionova has already assigned this ticket to @Rutam21.
It's best that you only work on the tickets assigned to you and keep up a healthy open-source contribution environment.

**Comment by Sayanta66** [comment]
It's unassigned

**Comment by ArmanChand** [comment]
The procedure is to comment on the ticket and get it assigned to yourself and as the ticket is assigned to someone it's best in the spirit of opensource to close this PR . There are already two tickets in your name that you should be contributing to. Cheers ✌

**Comment by lena-larionova** [comment]
Hi @Sayanta66, we cannot accept this submission as it does not align with Kong's branding standards. As well, another contributor is actively working on this issue, so I'm closing this PR to avoid duplicate work.

**Pull request closed without merging**
