### PR TITLE
docs(key-mgmt): import remote JWKs

### PR DESCRIPTION
**Pull request by jschmid1**
### Description

What did you change and why?
 
https://konghq.atlassian.net/browse/KAG-718

### Testing instructions

Accompanying PR -> https://github.com/Kong/kong/pull/10382

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by lena-larionova** [comment]
@jschmid1 I've just made a `release/gateway-3.3` branch. Could you please move this to target that branch?

**Comment by lena-larionova** [comment]
Based on the conversation in the linked eng ticket, I'm going to hold off reviewing until the implementation is settled. Ping me when you're ready for a doc review.

**Comment by hbagdi** [comment]
This is not in 3.3. @jschmid1 Correct?

**Comment by hbagdi** [comment]
Closing, please open again against 3.4.

**Pull request closed without merging**
