### PR TITLE
[DOCU-348] Admin API: rm del service for route

### PR DESCRIPTION
**Pull request by falondarville**
### Summary

Remove Admin API **Delete Service Associated to a Specific Route** endpoint from versions 1.3.x onward.

### Reason

Addresses [DOCU-348](https://konghq.atlassian.net/browse/DOCU-348)

### Testing

Latest:
https://deploy-preview-3740--kongdocs.netlify.app/gateway/2.8.x/admin-api/#delete-service

### CODE REVIEW

**Review by lena-larionova — COMMENTED** [review]
This is good for the docs side, but this is yet another thing that will need an update in the code repo as well. 

I did a bit of digging in the code repo and here's what I found:
Looks like you can specify a request type to ignore for a specific endpoint, and that works. For example:
https://github.com/Kong/kong/blob/master/autodoc/admin-api/data/admin-api.lua#L1234-L1237

```
      ["/plugins/:plugins/route"] = {
        DELETE = {
          endpoint = false,
        }
```
If you look at our docs, there is no entry for deleting a route via plugins, so we know it works:
https://docs.konghq.com/gateway/2.8.x/admin-api/, search the page for `/plugins/{plugin id}/route`


So you'll want to do the same thing for this endpoint (`["/routes/:routes/service"]`) and add it to the routes section, right above route entity fields for consistency:
https://github.com/Kong/kong/blob/master/autodoc/admin-api/data/admin-api.lua#L930

**Comment by falondarville** [comment]
Are you saying we should add `DELETE = false` rather than delete it outright?

**Review by lena-larionova — APPROVED** [review]
LGTM for the docs repo side!

**Comment by lena-larionova** [comment]
> Are you saying we should add DELETE = false rather than delete it outright?

We should do both. The work you did in this PR was necessary, since we don't regenerate old content. To avoid the same issue going forward, we should add `DELETE = false` for this endpoint in the code repo.

**Pull request merged**
