### PR TITLE
[DOCS-1607] Port 2.2 dev portal key auth self-hosted to 2.3

### PR DESCRIPTION
**Pull request by tlblessing**
https://konghq.atlassian.net/browse/DOCS-1607

See PR for 2.2.x  https://github.com/Kong/docs.konghq.com/pull/2527/files.

The Key Auth hub plugin docs are in a separate area and do not need to be ported.

Direct review link:

https://deploy-preview-2631--kongdocs.netlify.app/enterprise/2.3.x/developer-portal/administration/application-registration/enable-key-auth-plugin/

### CODE REVIEW

**Comment by lena-larionova** [comment]
FYI commit f3068ad isn't broken, I just skipped the workflow run, since there's two running simultaneously in this PR.

**Comment by tlblessing** [comment]
> FYI commit [f3068ad](https://github.com/Kong/docs.konghq.com/commit/f3068ad9a2bc4d9bd2e557e15f09d6a1dcff36a2) isn't broken, I just skipped the workflow run, since there's two running simultaneously in this PR.

That made me think it was broken but it would be nice if I had the ability to stop builds like I did before.

**Comment by lena-larionova** [comment]
> That made me think it was broken but it would be nice if I had the ability to stop builds myself like I did before.

Yep, that's why I called it out :) 
You always have the ability to skip the build/test action.

1. Click on the status dot beside a commit, then in the left nav, click on Build and Test. 
Screen Shot 2021-02-24 at 10 33 08 AM

2. On the top right of that page, click Cancel Workflow.
Screen Shot 2021-02-24 at 10 34 15 AM

**Comment by tlblessing** [comment]
> > That made me think it was broken but it would be nice if I had the ability to stop builds myself like I did before.
> 
> Yep, that's why I called it out :)
> You always have the ability to skip the build/test action yourself.
> 
> 1. Click on the status dot beside a commit, then in the left nav, click on Build and Test.
>    Screen Shot 2021-02-24 at 10 33 08 AM
> 2. On the top right of that page, click Cancel Workflow.
>    Screen Shot 2021-02-24 at 10 34 15 AM

I could've sown the cancel workflow button had stopped showing for me. But I see it now. And I remember you said there is a delay from when you click the button and when it actually stops. I expected like instant cancel.

**Review by lena-larionova — APPROVED** [review]

**Pull request merged**
