### PR TITLE
feat(plugin) add consumer_identifier_default, service_identifier_default and workspace_identifier_default

### PR DESCRIPTION
**Pull request by vm-001**
### Summary
Support identifier default for consumer_identifier, service_identifier and workspace_identifier

### Reason

https://konghq.atlassian.net/browse/FTI-4086

### Testing

I've already run this project and confirmed my change works.

### CODE REVIEW

**Comment by lena-larionova** [comment]
@vm-001 can you please rebase and point this PR to the `release/gateway-3.0` branch?

**Comment by Guaris** [comment]
I'll fix this branch since I rebased over main.

**Review by Guaris — CHANGES_REQUESTED** [review]
placeholder

**Review by Guaris — APPROVED** [review]

**Comment by vm-001** [comment]
Thank you！

**Pull request merged**
