### PR TITLE
Include sample: how can configure dbless with Visual Studio Code.

### PR DESCRIPTION
**Pull request by EwertonJordao**
Validate dbless configuration with Visual Studio Code and SchemaStore.

### Summary

Include schema validation in schemastore and use that with redhat extension in Visual Studio Code. 

### Reason

The steps for test on doc changes

### CODE REVIEW

**Comment by EwertonJordao** [comment]
review:general

**Comment by Guaris** [comment]
Thank you for opening this PR and contributing to our documentation. We try to avoid documenting third-party plugins and solutions except in cases where we have designed Kong to work in conjunction with that third-party tool, like SSO providers, or cloud computing providers. We do this to avoid having to maintain documentation for third-party tools. For this reason, I can't merge your PR. I appreciate your contribution and I hope you continue to contribute to our docs, and other open source projects like this one. Thank you!

**Comment by EwertonJordao** [comment]
> Thank you for opening this PR and contributing to our documentation. We try to avoid documenting third-party plugins and solutions except in cases where we have designed Kong to work in conjunction with that third-party tool, like SSO providers, or cloud computing providers. We do this to avoid having to maintain documentation for third-party tools. For this reason, I can't merge your PR. I appreciate your contribution and I hope you continue to contribute to our docs, and other open source projects like this one. Thank you!

I created this PR because always see in the community that it's so hard to configure kong with dbless mode, we can validate with decK but with this simple configuration we see validation JIT in a code editor and fix issues, decK is useful in CI/CD environment but for first contact, I think the best way to exploration mode is edit with an editor.

**Comment by Guaris** [comment]
> I created this PR because always see in the community that it's so hard to configure kong with dbless mode, we can validate with decK but with this simple configuration we see validation JIT in a code editor and fix issues, decK is useful in CI/CD environment but for first contact, I think the best way to exploration mode is edit with an editor.

Understood, after discussion with our team we've decided that your contribution would be a good fit at `src/deck/faqs.md`.

**Review by Guaris — APPROVED** [review]

**Comment by Guaris** [comment]
@EwertonJordao could you please fill out this form: https://konghq.com/conferences/kong-summit/hackathon to make sure this PR counts towards the Kong Hackathon

**Comment by EwertonJordao** [comment]
> @EwertonJordao could you please fill out this form: https://konghq.com/conferences/kong-summit/hackathon to make sure this PR counts towards the Kong Hackathon

@Guaris Thanks for share this link.

**Pull request merged**
