### PR TITLE
Remove konghq trailing links

### PR DESCRIPTION
**Pull request by mheap**
### Summary
Remove the trailing slash from any links to konghq.com

### Reason
SEO impact for the marketing team

### Testing

I ran the broken link checker on the whole site using the following instructions:

```
cd broken-link-checker
npm ci
netlify dev
node full.js --host http://localhost:8888
```

There were no new broken links (some old ones which we can fix in a followup PR)

### CODE REVIEW

**Comment by mheap** [comment]
Changes made with the following:

```
HTML:

grep -lEr "https://konghq.com/.*/" app | xargs gsed -i 's/\("https:\/\/konghq.com\/.*\)\/"/\1"/'

Markdown: 

grep -lEr "https://konghq.com/.*/“ app | xargs gsed -i 's/\((https:\/\/konghq.com\/.*\)\/)/\1)/'
```

**Comment by mheap** [comment]
There are some broken links, but none that are related to the changes made today. With that in mind, I'd like to ignore them today and revisit after the 3.0 release + archiving of old content.

Vale is erroring too, but given this is an automated update I think we can ignore the suggestions.

**Review by Guaris — APPROVED** [review]

**Comment by mheap** [comment]
@lena-larionova This PR specifically targets https://www.konghq.com and https://konghq.com which are configured to run _without_ a trailing slash.

The slides shared are an issue, but that's separate to what this PR aims to address. I believe we should fix old redirects to point to the trailing slash URLs, fwiw

**Review by lena-larionova — APPROVED** [review]
> The slides shared are an issue, but that's separate to what this PR aims to address. I believe we should fix old redirects to point to the trailing slash URLs, fwiw

In that case, feel free to ignore for now, and this one LGTM.

**Pull request merged**
