### PR TITLE
fix(mesh-policy): fixed paths to kong mesh specific policies

### PR DESCRIPTION
**Pull request by Automaat**
### Description

What did you change and why?
 
This issue: https://github.com/Kong/docs.konghq.com/issues/5381 is still not fixed. So I am reopening [pr](https://github.com/Kong/docs.konghq.com/pull/5427) with the fix

### Testing instructions

Netlify link: 

### Checklist 

- [ ] Review label added 
- [ ] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by cloudjumpercat — DISMISSED** [review]
LGTM! Thanks for adding these!

**Comment by cloudjumpercat** [comment]
@Automaat I think the broken link test is failing because we need to add a few things since those pages are used twice in the sidebar.

Add these to the `_redirects` file:
```
/mesh/:version/features/meshglobalratelimit     /mesh/:version/policies/meshglobalratelimit
/mesh/:version/features/meshopa     /mesh/:version/policies/meshopa
```

Since we have `generate: false` already set for the items in the "Features" section, I think that just adding these redirects should fix the problem.

**Comment by Automaat** [comment]
@cloudjumpercat I found a way for this to work, and to structure these docs in a more natural way. But broken link check is still failing on some strange `svg` files, could you help with that?

**Comment by cloudjumpercat** [comment]
@Automaat Ah, I think that the file name somehow was switched to "kong-mesh" there instead of "kuma". [In this file on this line](https://github.com/Kong/docs.konghq.com/blob/78fb5cf235bf583aa3cbcd533bf9e7b1613181ba/app/_src/mesh/index.md?plain=1#L144) it should be:

`  Kuma service mesh multi zone deployment`

**Pull request merged**
