### PR TITLE
chore: bump .ruby-version to 3.1.3 to allow building on arm64

### PR DESCRIPTION
**Pull request by pmalek**
### Description

Bump ruby version check from 3.1.2 to 3.1.3 so that folks running arm64 can also build docs locally

### Testing instructions

I've tested it with

```
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [arm64-darwin22]
```

installed via `ruby-install ruby 3.1.3`.

### CODE REVIEW

**Comment by pmalek** [comment]
Guess, this would have to be figured out somehow:

```
/home/runner/work/docs.konghq.com/docs.konghq.com/vendor/bundle/ruby/3.1.0/gems/liquid-c-4.0.0/ext/liquid_c
make DESTDIR\= sitearchdir\=./.gem.20230303-1703-5g5f1u
sitelibdir\=./.gem.20230303-1703-5g5f1u
compiling block.c
block.c: In function ‘init_liquid_block’:
block.c:126:6: error: old-style function definition
[-Werror=old-style-definition]
  126 | void init_liquid_block()
      |      ^~~~~~~~~~~~~~~~~
block.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been
intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have
been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may
have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make: *** [Makefile:247: block.o] Error 1
```

**Comment by fabianrbz** [comment]
@pmalek have you tried just bumping ruby? that error is due to some of the dependencies updates

**Comment by pmalek** [comment]
> @pmalek have you tried just bumping ruby? that error is due to some of the dependencies updates

You mean from which version to which one? I'm running 3.1.3 and I can't get 3.1.2 because I can't build it for arm64.

**Comment by fabianrbz** [comment]
The ruby version is fine, just drop the changes made to the `Gemfile` and `Gemfile.lock`

**Comment by pmalek** [comment]
> The ruby version is fine, just drop the changes made to the `Gemfile` and `Gemfile.lock`

Oh, OK. Sure thing. Update the PR, PTAL.

**Comment by pmalek** [comment]
@fabianrbz Same error as in https://github.com/Kong/docs.konghq.com/pull/5243#issuecomment-1453634989 😿

**Comment by fabianrbz** [comment]
@pmalek ah sorry, I remember this issue, 3.1.3 and 3.2 fail to install liquid-c on Ubuntu, that's why I haven't updated it. See [this](https://github.com/jekyll/jekyll/pull/9195) Looks like bumping liquid-c to v4.0.1 fixes it. Let me try that.

**Review by fabianrbz — APPROVED** [review]

**Pull request merged**
