### PR TITLE
docs(ce/getting-started) typo in secure-services section

### PR DESCRIPTION
**Pull request by malhotraamit236**
* change mock to mocking in admin api calls

### CODE REVIEW

**Comment by lena-larionova** [comment]
@malhotraamit236 Sorry for the confusion, but the initial path is correct: `mocking` is the name and `/mock` is the path, as set earlier in the getting started guide: https://docs.konghq.com/getting-started-guide/latest/expose-services/#add-a-route

**Comment by malhotraamit236** [comment]
> @malhotraamit236 Sorry for the confusion, but the initial path is correct: `mocking` is the name and `/mock` is the path, as set earlier in the getting started guide: https://docs.konghq.com/getting-started-guide/latest/expose-services/#add-a-route

**Comment by malhotraamit236** [comment]
@lena-larionova I was referring to `http :8001/routes/mock/plugins name=key-auth` in https://docs.konghq.com/getting-started-guide/latest/secure-services/ 

I tried to add plugin to a path and got:
```
HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 23
Content-Type: application/json; charset=utf-8
Date: Mon, 04 May 2020 17:54:45 GMT
Server: kong/2.0.4
X-Kong-Admin-Latency: 1

{
    "message": "Not found"
}
```
But if I do `http :8001/routes/mocking/plugins name=key-auth` it is successful.

**Comment by lena-larionova** [comment]
> But if I do `http :8001/routes/mocking/plugins name=key-auth` it is successful.

Hmm, I just tested it, and you are right. This is an odd/confusing design choice. Thanks for double-checking!

**Pull request merged**
