### PR TITLE
Fix Mesh changelog duplicate

### PR DESCRIPTION
**Pull request by cloudjumpercat**
### Description

What did you change and why?

- There were two Mesh changelogs after https://github.com/Kong/docs.konghq.com/pull/5782  was merged. This fixes that so there's just one because it was causing issues on local `main` branches.

 
Include any supporting resources, e.g. link to a Jira ticket, GH issue, FTI, Slack, Aha, etc.

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by lena-larionova — APPROVED** [review]
looks like no conflicts, so lgtm

**Comment by cloudjumpercat** [comment]
> looks like no conflicts, so lgtm

@lena-larionova I'm just going to check to see if it will pull the correct changelog in the nav files in the Netlify preview (since I didn't change any of the nav files, I thought it might use the right name anyways since it's just a url and not src pointing to the file?)

**Comment by lena-larionova** [comment]
@cloudjumpercat I don't think this will do it:

> @cloudjumpercat
[Rename CHANGELOG.md to changelog.md](https://github.com/Kong/docs.konghq.com/pull/5793/commits/578319f2e763c2a52a73604dee89372fadeb8a2a) 

The file now has no front matter, so it can't be generated directly. I think you need to use the contents of the old changelog.md.

**Comment by curiositycasualty** [comment]
Running into this issue on my mac (case-insensitive filesystem) since both `changelog.md` and `CHANGELOG.md` flip flop as unstaged changes according to git.

**Comment by cloudjumpercat** [comment]
> Running into this issue on my mac (case-insensitive filesystem) since both `changelog.md` and `CHANGELOG.md` flip flop as unstaged changes according to git.

@curiositycasualty Yep, the docs team ran into the same issue as well and we're working on the fix right now :)

**Comment by cloudjumpercat** [comment]
Just an FYI, the broken link checker is failing because the links are pointing to a private GH repo. I'm going to revert this and use the old changelog until we can come up with a better solution for automation with Fabian and Charly.

**Pull request merged**
