### PR TITLE
chore(deps): bump kumahq/kuma-website from de4e348f to 77a7ab96

### PR DESCRIPTION
**Pull request by kong-docs**
Auto upgrade PR log:

77a7ab967de59578caf338a2c17991ae7a856384 ci(vale): enforce heading capitalization (kumahq/kuma-website#1992)
630378e1a28835fa13a791534b8b07efc5906e5e fix(gateway): don't use MeshGateway tags that cannot be referenced from Mesh*Route (kumahq/kuma-website#1991)
f5a4a410e4ce52c5e5510cba7cd8e43b59eb79f9 feat(meshservice): Add meshservice checkbox to tabs component (kumahq/kuma-website#1985)
156d1d5807389c1f75c5d6bd5645a4b9d5ee2d6c docs(policies): rework intro page and add concepts (kumahq/kuma-website#1956)
57ae7fc41706383f04a67527d217dc2e11cbf480 chore(contributing): update docs (kumahq/kuma-website#1964)
632782933063913b2538e627b07a1e1f529ecc75 fix(guide): improve progressively rolling in strict mtls doc (kumahq/kuma-website#1967)
257db537704156f507bfdc90a688aa15da31dced docs(install): replace Kind with Minikube for simple test installations (kumahq/kuma-website#1971)
ff5ac89fd450c3777894c06fe9c1590cc3993f74 feat(guide): add guide for namespace scoped policies (kumahq/kuma-website#1910)
cb373880499cd7ecfc6fb03f33e549dfd4278ad6 ci(vale): add mermaid keywords to accept.txt (kumahq/kuma-website#1989)
08fd96b51a79ec7e9ea3ae116c7475764e0c5c68 ci(vale): reject controlplane/control-plane and dataplane/data-plane (kumahq/kuma-website#1977)
8955d3e84ac0b895cdf865407f7499c227198f87 ci(vale): fix reporter, only annotate errors (kumahq/kuma-website#1984)
dc0507957417be5c4d99ca6bdb1addc22e8b6dd3 fix(quickstart): don't use MeshService in spec.targetRef (kumahq/kuma-website#1986)

Triggered by [action](https://github.com/Kong/docs.konghq.com/actions/runs/11450877511).

### CODE REVIEW

**Comment by cloudjumpercat** [comment]
@fabianrbz Looks like `dev` on the Kong Mesh site is getting a 404: https://deploy-preview-8066--kongdocs.netlify.app/mesh/dev/ . But it seems to be working just fine on the Kuma site: https://kuma.io/docs/dev/quickstart/kubernetes-demo/

Do you know why it might be failing like this?

**Comment by fabianrbz** [comment]
2.10.0 is flagged as dev, but there isn't a 2.10 docs_nav_file, that's
probably why.

**Comment by jijiechen** [comment]
@fabianrbz @cloudjumpercat 
Sorry for the confusing. I think this is caused by the situation that we are in the middle of a minor version releasing. 
Once the following PR is merged, this failure probably will be solved automatically:
https://github.com/Kong/docs.konghq.com/pull/8062

**Comment by cloudjumpercat** [comment]
@jijiechen That fixed it, thanks!

**Review by cloudjumpercat — APPROVED** [review]

**Pull request merged**
