### PR TITLE
Add volume

### PR DESCRIPTION
**Pull request by aaronhmiller**
**NOTE**: Please read the CONTRIBUTING.md guidelines before submitting your patch,
and ensure you followed them all:

https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md

### Summary

Add --volumes instructions to map license when using Docker on Windows.

### Full changelog

* Edited docs to add guidance for Docker for Windows users based on user input

### Checklist:

- [ ] [Commit message & atomicity](https://github.com/Kong/docs.konghq.com/blob/master/CONTRIBUTING.md#commit-atomicity) checked N/A
- [ ] Documentation  N/A
- [x] Spellchecked my updates
- [x] Ready to be merged

### CODE REVIEW

**Comment by catfishbluefish** [comment]
screen shot 2018-08-13 at 9 05 17 am

**Comment by aaronhmiller** [comment]
Thanks. When I go to check the changes, looks same as before and wrapping properly. Can't get it to display as you show, could the markdown be showing differently?

**Comment by leevye** [comment]
I reformatted the longer sections into code blocks - if this looks OK to you I will merge
screen shot 2018-08-14 at 11 28 11 am

**Comment by aaronhmiller** [comment]
Thanks! LGTM

**Pull request merged**
