### PR TITLE
update http-log description: custom headers

### PR DESCRIPTION
**Pull request by javierguerragiraldez**
document new parameters, custom headers and a couple HTTP miscellaneous

### CODE REVIEW

**Comment by tlblessing** [comment]
@javierguerragiraldez is there a doc version bump needed for these updates? Is this for 2.3? Also please see my stalled PR on this pluginhttps://github.com/Kong/docs.konghq.com/pull/2393.

**Comment by javierguerragiraldez** [comment]
sorry, i missed your other PR #2393.  lets merge both.

AFAICT, the `headers` parameter is already available in Kong 2.2

**Comment by tlblessing** [comment]
> sorry, i missed your other PR #2393. lets merge both.
> 
> AFAICT, the `headers` parameter is already available in Kong 2.2

Now I know to tag you next time. Thanks for your responses. I'll get my edits into your PR.

**Review by kikito — APPROVED** [review]

**Comment by javierguerragiraldez** [comment]
closed in favor of #2393

**Pull request closed without merging**
