### PR TITLE
Copydited the entire document for issue #3247

### PR DESCRIPTION
**Pull request by Sayanta66**
### Summary

Copedited the entire doc according to Kong style guide. Used simple wording and active voices. Fixed article and punctuation error. This PR completely resolves any error and will potentially close the issue.

### Reason

Issue #3247

### CODE REVIEW

**Comment by Sayanta66** [comment]
Note: The last pull request on this issue has errors and I commented first on this issue and started working on it as soon as it dropped. So, I submitted this PR. Please do a fair review of both the PRs and then give the judgement accordingly. I am not doing this for money or t-shirt but the contributions on the Kong Page will boost both my Linkedin and GitHub profile.

**Comment by Techie-Manju** [comment]
@Sayanta66 It seems that you have been answered your way on this issue. You started taking away tickets of another contributor. You have even done the same for the issue https://github.com/Kong/docs.konghq.com/issues/3205, where another contributor has commented first but still you have barged in like that. We as an open source community can clearly see who started things and whose making things ugly. Even your explanation clearly portrays how concerned you are because of your guilt. As much as I can remember, you were spamming PRs in Mattermost Docathon as well out of which maximum were closed for being invalid. @Rutam21 started late there but still he managed to meaningfully contribute the most and is currently the Mattermost MVP of the month. I believe he has lot to offer in this repo as well. So, kindly cut the crap and refrain from barging in everywhere.

**Comment by Sayanta66** [comment]
The PRs were closed because I accidentally deleted the actual forked repository in Mattermost Docathon. You are paid employee of someone I guess. So please refrain from commenting under my  PRs and Repos.... otherwise I will Report you to the police for online harrasment

**Comment by Techie-Manju** [comment]
The PRs in Mattermost clearly have comments that says they're invalid. Don't try to fool everyone around. You were creating duplicate PRs as well in there. Moreover, let me make this clear to you that this is an open source project and the community has got all the rights to put in their feedbacks. Get the definitions clear first and secondly, I am not paid by anyone. Your comment only triggered me as you mentioned you're not here for T-shirt or money as if all other contributors in here are only after this. Watch your actions and words first and then suggest others. 🤞

**Comment by Sayanta66** [comment]
Oh well...you are clearly trying to tamper here. And why are you even in my repo. I am seriously saying it. I take anti anxiety meds and I don't have a lot of patience. Don't bug here or the next thing you will face is legal actions. And why my last Mattermost PRs were closed , contact Justin Greffen. She will tell you everything. Now, don't bug me and do your own thing. Otherwise, my patience will run out.

**Comment by Techie-Manju** [comment]
Oh! So, now we are talking about medicines here. Well, May God bless you then.
@lena-larionova Let's keep it a positive and productive space for all contributors and please assign the next copyedit ticket to me. I am quite excited to start with my 1st PR contribution.

**Comment by Sayanta66** [comment]
Yeah! Why? Do you have any stigma with it? There are lots of things available. Stop trolling from a fake account.

**Comment by reynolek** [comment]
Kong prides itself on Open Source and on fostering a strong community of those committed to making improvements for other users of our products.

GitHub is not the place for arguing, personal attacks or threats. Please keep discussions civil, and on topic to the PR.

**Pull request closed without merging**
