### PR TITLE
fix: mention required secret field for JWT plugin in KIC how to

### PR DESCRIPTION
**Pull request by programmer04**
### Description

Fix how to guide, it was reported by the user in the discussion

https://github.com/Kong/kubernetes-ingress-controller/discussions/5146

indeed field `secret` is missing you can read about this requirement at https://docs.konghq.com/hub/kong-inc/jwt/#create-a-jwt-credential see
image

This PR adds it in the required places.

 

### Testing instructions

Preview link: https://deploy-preview-6502--kongdocs.netlify.app/kubernetes-ingress-controller/latest/plugins/acl/#provision-jwt-credentials

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Review by Rajakavitha1 — APPROVED** [review]
LGTM!

**Comment by programmer04** [comment]
Thanks, @Rajakavitha1 for pointing it out. It's a problem with indentation when it's copied. I fixed it. PTAL

**Comment by Rajakavitha1** [comment]
> Thanks, @Rajakavitha1 for pointing it out. It's a problem with indentation when it's copied. I fixed it. PTAL

Thank you for making the fix @programmer04 . one more minor fix. Please add an additional line so that the setence does not become the part of the results.
Screenshot 2023-11-14 at 5 19 04 PM

**Comment by programmer04** [comment]
It's done @Rajakavitha1, thanks for the cooperation

**Review by lena-larionova — APPROVED** [review]
Looks like this one has been ready for a while - LGTM

**Pull request merged**
