### PR TITLE
feat(http-log): Add docs for logged header allow list

### PR DESCRIPTION
**Pull request by ItsKaleb**
This PR adds the supporting documentation for PR #11427. Functional changes are to implement an allow list for which request/response headers should be included in log entries.

### Description

Add supporting documentation for 
https://github.com/Kong/kong/pull/11427

### Testing instructions

Netlify link: 

### Checklist 

- [x] Review label added 
- [x] PR pointed to correct branch (`main` for immediate publishing, or a release branch: e.g. `release/gateway-3.2`, `release/deck-1.17`)

### CODE REVIEW

**Comment by acgoldsmith** [comment]
Hi @ItsKaleb , thanks for this PR. Could you please point to  `release/gateway-3.5 `rather than main? Thanks.

**Comment by ItsKaleb** [comment]
Thanks @acgoldsmith, will do that, yep.

**Comment by cloudjumpercat** [comment]
@ItsKaleb Thanks for fixing some of those Vale errors! I'm happy to help with the others. 

I think maybe some extra commits were pulled in when the base branch was changed to `release/gateway-3.5`, so I think the easiest way to fix it would be for me to create a new PR for you and I can cherry pick the commits you specifically made. I think the only ones with doc changes you made were https://github.com/Kong/docs.konghq.com/pull/5984/commits/8ca48b04fb6051d429eedf2f67a236fb5ce869ec and https://github.com/Kong/docs.konghq.com/pull/5984/commits/271cce11c22d6a3dd6cb0e416b1100d903bc0ddb, correct? The rest were either rebases/updating the branch or commits accidentally pulled in, I think?

Then I can help by getting those config names added to our Vale ignore file so Vale ignores them.

**Comment by ItsKaleb** [comment]
Ah yes, thanks @cloudjumpercat 
My apologies, I'm more familiar with Bitbucket than Github, so not surprised that I messed that up.
I'll do as you suggested and raise a new PR, should be able to sort that soon.

**Comment by cloudjumpercat** [comment]
@ItsKaleb No worries! If you'd like, I can always do the cherry pick to the new PR as well.

**Comment by ItsKaleb** [comment]
Just to provide an update, I'm currently working through some hiccups with the feature branch in the main repo. Once things are sorted there, I'll revisit this PR and get the docs for the new feature fixed up.

**Comment by Guaris** [comment]
I've removed the Gateway 3.5 milestone the corresponding PR does not look like it will be added to the 3.5 release
https://github.com/Kong/kong/pull/11427

If I am incorrect please re-add the milestone and tag me.

**Pull request closed without merging**
