### PR TITLE
docs(ee) Adding images to Arch patterns doc

### PR DESCRIPTION
**Pull request by UkiahSmith**
Added images, updated page title.

### CODE REVIEW

**Comment by coopr** [comment]
I'm a little confused - in EE 0.31 docs I see both https://getkong.org/docs/enterprise/0.31-x/kong-implementation-checklist/ and https://getkong.org/docs/enterprise/0.31-x/kong-architecture-patterns/ - in EE 0.32 docs I see only https://getkong.org/docs/enterprise/0.32-x/kong-architecture-patterns/ - the Implementation Checklist seems to be missing from EE 0.32 docs. Can you clarify what your PR is intending to change?

**Comment by UkiahSmith** [comment]
This PR does not change the implementation checklist. It is adding images to one single document that has two version

These are the files affected:
app/docs/enterprise/0.31-x/kong-architecture-patterns.md
app/docs/enterprise/0.32-x/kong-architecture-patterns.md

**Comment by coopr** [comment]
@UkiahSmith can you see if you can resolve the conflicts in this PR? TIA!

**Comment by coopr** [comment]
Ran it locally, LGTM!

**Pull request merged**
