### PR TITLE
doc(kic) add version 2.2

### PR DESCRIPTION
**Pull request by rainest**
Add KIC 2.2 and the new Gateway API guide.

### Summary
Adds KIC 2.2. Non-metadata changes are in the version reference, CLI args, and Gateway API guide.

### Reason
KIC 2.2 will be released. Hold until https://github.com/Kong/kubernetes-ingress-controller/issues/2231 is complete.

### Testing
Netlify review. Gateway steps verified independently.

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]

**Comment by rainest** [comment]
Is https://docs.konghq.com/contributing/markdown-rules/#markdown-front-matter out of date, or did I mess something up? https://deploy-preview-3621--kongdocs.netlify.app/kubernetes-ingress-controller/2.2.x/guides/using-gateway-api/ doesn't appear to have any alpha banner, but does have that in front matter: https://github.com/Kong/docs.konghq.com/pull/3621/files?show-viewed-files=true&file-filters%5B%5D=#diff-38bab76bb15fbf90ef432a6d99f547be84e5a391dfbbc41cc7bd4970b916fd6dR3

**Review by shaneutt — CHANGES_REQUESTED** [review]
I noticed we have the new Gateway guide in here already: I think we should pull that and allow it to be its own follow up PR: we're going to want to review that in isolation, and @scseanchow specifically wants to look it over.

**Review by shaneutt — APPROVED** [review]

**Comment by lena-larionova** [comment]
> Is https://docs.konghq.com/contributing/markdown-rules/#markdown-front-matter out of date, or did I mess something up? https://deploy-preview-3621--kongdocs.netlify.app/kubernetes-ingress-controller/2.2.x/guides/using-gateway-api/ doesn't appear to have any alpha banner, but does have that in front matter: https://github.com/Kong/docs.konghq.com/pull/3621/files?show-viewed-files=true&file-filters%5B%5D=#diff-38bab76bb15fbf90ef432a6d99f547be84e5a391dfbbc41cc7bd4970b916fd6dR3

You didn't do anything wrong, the layout is missing conditional logic for handling `alpha` and `beta`. Not sure what happened there. Fixing that in https://github.com/Kong/docs.konghq.com/pull/3625.

**Comment by rainest** [comment]
@lena-larionova gotcha. Gateway page is now in https://github.com/Kong/docs.konghq.com/pull/3622 instead anyway, so assuming the link checker is happy now that I've purged the leftover menu entry this should be all set.

**Comment by rainest** [comment]
Well, still unhappy, but IDK why:

```
 Broken links:
[
  {
    "page": "https://deploy-preview-3621--kongdocs.netlify.app/kubernetes-ingress-controller/2.2.x/guides/setting-up-custom-plugins/",
    "text": "use external plugins in container and Kubernetes",
    "target": "https://deploy-preview-3621--kongdocs.netlify.app/gateway/latest/reference/external-plugins/#use-external-plugins-in-container-and-kubernetes",
    "reason": "BLC_UNKNOWN"
  }
]
```

Amusingly, BLC also doesn't know why, but the link appears fine, anchor and all:

https://deploy-preview-3621--kongdocs.netlify.app/gateway/2.7.x/reference/external-plugins/#use-external-plugins-in-container-and-kubernetes

**Comment by lena-larionova** [comment]
Yeah, it's flaky sometimes, and you gave it a lot of topics to check. Looks like it's fine though, so I marked the check as validated.

**Review by lena-larionova — APPROVED** [review]

**Pull request merged**
