### PR TITLE
Add portal_auth_app to property reference

### PR DESCRIPTION
**Pull request by tlblessing**
https://konghq.atlassian.net/browse/DOCS-1283

Also mentioned hybrid mode limitation with OAuth2.

There were many typos present in the property reference file. I fixed those, and edited some for more active voice in spots.

Direct review link for new entry:
https://deploy-preview-2282--kongdocs.netlify.app/enterprise/2.1.x/property-reference/#dev-portal-application-registration-authentication-strategy

### CODE REVIEW

**Comment by tlblessing** [comment]
> The description you have provided for portal_app_auth 👍

Thanks @Jlawlzz !

**Comment by lena-larionova** [comment]
The edits you made are great, but unfortunately, this is one of the files that's automated in the CE docs and is going to get overwritten as soon as we get that automation working for EE too. I'm not sure that it makes sense to go through and fix typos in that context.

**Comment by tlblessing** [comment]
> The edits you made are great, but unfortunately, this is one of the files that's automated in the CE docs and is going to get overwritten as soon as we get that automation working for EE too. I'm not sure that it makes sense to go through and fix typos in that context.

@lena-larionova There are many typos in that doc and that reflects poorly on Kong. I'm happy to edit the source.
@GayleNeumann you still have this PR on the same file. Are you going to merge that soon? I can rebase my PR if so.

**Comment by tlblessing** [comment]
This file is not generated from source code. Closing PR per Lena.

**Pull request closed without merging**
