### PR TITLE
fix docs for developer-portal collections

### PR DESCRIPTION
**Pull request by sanyer**
I was trying to change route for rendered spec file using `x-headmatter` and stumbled upon collections having issues.
I've fixed only the obvious mistakes.
I don't know if it a required attribute or if other (route, output) attributes are correct.

### CODE REVIEW

**Comment by tlblessing** [comment]
Requested reviews from team-devx members. I do not see a team dev-x entry in github.

**Comment by tlblessing** [comment]
> [CLA assistant check](https://cla-assistant.io/Kong/docs.konghq.com?pullRequest=2479)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/docs.konghq.com?pullRequest=2479) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/docs.konghq.com?pullRequest=2479) it.

@sanyer can you please sign the CLA?

**Review by HenriPro — APPROVED** [review]
Good catch @sanyer, LGTM. I took another look at the whole page, and did not see anything else outstanding.

**Comment by tlblessing** [comment]
> Good catch @sanyer, LGTM. I took another look at the whole page, and did not see anything else outstanding.

Thank you @HenriPro for your review!

**Review by tlblessing — APPROVED** [review]

**Comment by tlblessing** [comment]
Due to issues with the CLA, I will rebuild this correction in another PR.

**Review by Bradamant3 — APPROVED** [review]
@sanyer with many many apologies for the ridiculous long delay. I _think_ we can proceed with approving and merging without the CLA, which was mistakenly applied to this repo and the issues have only recently been sorted out.

**Pull request merged**
